manifests/profile/keepalived.pp
spec/classes/profile/keepalived_spec.rb
templates/profile/keepalived/sysctl.conf.erb

Resolves AEIM-1257, set to merge into the aeim-1247 branch

Manage /etc/sysctl.d/keepalived.conf

---

data/common.yaml
manifests/profile/vmhost/host.pp
spec/classes/profile/vmhost/host_spec.rb

I've also made (but not committed) the necessary changes to lensoftruth. I'll push and run r10k when this gets merged.

AEIM-1273 - Remove vmhost defaults parameter

---

data/common.yaml
manifests/profile/haproxy.pp
spec/classes/profile/haproxy_spec.rb

With AEIM-1248 this should be genericized per front-end.

AEIM-1249: copy directory of ssl certs

---

data/common.yaml
lib/puppet/functions/find_all_files_under.rb
manifests/profile/puppet/master.pp
spec/classes/profile/puppet/master_spec.rb
spec/functions/find_all_files_under_spec.rb

Still need to actually use the function in the puppet code.

AEIM-1325 - Manage fileservers with a function

---

manifests/profile/apt.pp
spec/classes/profile/apt_spec.rb
spec/classes/profile/elastic/filebeat/prospectors/ulib_spec.rb
spec/classes/role/www_lib_webhost_spec.rb

The location & apt key should be defined via hiera.

AEIM-1449: allow adding a "local" apt repo

---

manifests/cpan.pp
manifests/profile/hathitrust/perl.pp

This is not a beautiful implementation, but it should do the trick.
There is a reasonable check in the unless that just loads the module.
The defined type sits at the nebula level, which may not be right for
the long term.

AEIM-1428 - Add CPAN modules to HTVM

---

data/common.yaml
manifests/haproxy_service.pp
spec/defines/haproxy_service_spec.rb

I haven't tested this yet—I'll comment here once I have.

AEIM-1658 - Retrieve errorfiles over https

---

manifests/profile/hathitrust/apache.pp

Resolves AEIM-1652
This should delete the directories and all of their contents,
recursively.

Purge apache conf-enabled,available

---

manifests/profile/hathitrust/shibboleth.pp

This should be everything remaining needed to start up and run shibd.

AEIM-1678, AEIM-1684: odbc connector, shib defaults

---

data/common.yaml
manifests/profile/apt.pp
manifests/profile/dns/smartconnect.pp
manifests/profile/elastic.pp
manifests/profile/hathitrust/mounts.pp
manifests/profile/hathitrust/shibboleth.pp
manifests/profile/networking/keytab.pp
manifests/profile/networking/private.pp
spec/classes/profile/apt_spec.rb
spec/classes/role/htvm_webhost_spec.rb
spec/default_facts.yml
spec/fixtures/hiera/deb_server_config.yaml
spec/fixtures/hiera/default.yaml
spec/fixtures/hiera/default_config.yaml
spec/spec_helper.rb

- Ensures apt-get update runs before trying to install packages
- Ensures private network is up before trying to do Isilon mounts
- Moves nonsense values from data/common.yaml to spec fixture

Fix issues with first run on a new node

---

manifests/profile/geoip.pp
spec/classes/profile/geoip_spec.rb
spec/fixtures/hiera/hathitrust.yaml

uses debian stretch package for geoipupdate

AEIM-1677: install & configure geoipupdate

---

.fixtures.yml
manifests/profile/logrotate.pp
manifests/profile/unison.pp
metadata.json
spec/classes/profile/logrotate_spec.rb
spec/classes/profile/unison_spec.rb
spec/defines/unison_client_spec.rb

Since this is using a new module, I'd like to test it in an environment before merging into production, to make sure the module does what we want.

AEIM-1057 - Add logrotate to unison

---

manifests/profile/moku.pp
manifests/profile/named_instances.pp
spec/defines/named_instance/solr_params_spec.rb
spec/defines/named_instance_spec.rb

- ensure $init_directory exists in nebula::profile::moku
- correct instance_title -> instance in exported resource collector for
solr cores
- move specs for solr_core exports to solr_params_spec

Address feedback on #98

---

manifests/profile/nodejs.pp
manifests/role/cron_runner.pp
spec/classes/role/cron_runner_spec.rb

See top-level comment in manifests/role/cron_runner.pp

AEIM-1865: role to run cron jobs

---

manifests/profile/hathitrust/apache.pp

Adds request time duration to the end of the combined Apache log.

AEIM-1874 Add request time duration to the Apache log

---

manifests/named_instance.pp
manifests/named_instance/app.pp
spec/defines/named_instance/app_spec.rb
spec/defines/named_instance_spec.rb

Resolves AEIM-2030
Resolves AEIM-2031
Resolves AEIM-2032

Add data, log, tmp paths to named_instance

---

manifests/named_instance.pp
spec/defines/named_instance_spec.rb

Add infrastructure.instance_name to named_instance json

---

manifests/role/cron_runner.pp

This isn't the right way to handle spot, but the right way kind of depends on what we go with regarding vault or however we decide to store secrets, so I'm inclined to leave this as it is until we figure out exactly how we want to deal with spot's keys and the propagation of ae-utils in general.

Get tests passing again

---

manifests/profile/haproxy.pp
manifests/profile/networking/firewall/ssh.pp

Not the best way to do it maybe, but this will get it done, and it'll be easy enough to revisit once we have something working.

AEIM-2116 - Open 6443 on haproxy servers

---

manifests/profile/hathitrust/apache.pp

Syntax supplied by @roger looks good to me. Sending this though for formality + testing.

expire hathitrust CSS and JS after 6h per AE-5982

---

spec/defines/named_instance/proxy_spec.rb
templates/named_instance/proxy_vhost.erb

The specs are rather brittle especially with regard to spacing, so
there's definitely a conversation to have about what we ought to be
testing here, how much should be migrated to the puppet apache module
(eventually) and what we should test then

AEIM-2166: Unroll proxy vhost macros

---

manifests/profile/base.pp
manifests/profile/hathitrust/dependencies.pp
manifests/profile/networking/private.pp
manifests/role/aws.pp
manifests/role/deploy_host.pp
manifests/role/hathitrust.pp
manifests/role/minimum.pp
manifests/role/umich.pp
spec/classes/profile/base_spec.rb

Replace every if statement that required Debian 9 to instead require Debian
and exclude Debian Jessie, thus adding preliminary support for Ubuntu and
Buster.

[WIP] Update branching logic to allow Debian >= 9 and Ubuntu

---

.rubocop.yml
.travis.yml

...and fix a Rubocop config complaint

Enable Slack notifications

---

.fixtures.yml
doc/adr/0003-run-kubernetes-locally.md
doc/adr/0004-roll-our-own-kubernetes-profile.md
doc/adr/0005-stack-k8s-controllers-with-etcd.md
doc/adr/0006-use-calico-for-kubernetes-networking.md
doc/adr/0007-only-manage-certain-netfilter-chains-in-kubernetes-machines.md
doc/adr/0008-dedicate-separate-haproxy-machines-for-load-balancing-kubernetes.md
manifests/profile/docker.pp
manifests/profile/kubernetes.pp
manifests/profile/kubernetes/haproxy.pp
manifests/profile/kubernetes/stacked_controller.pp
manifests/profile/kubernetes/worker.pp
manifests/profile/networking/firewall.pp
manifests/role/kubernetes/controller.pp
manifests/role/kubernetes/gateway.pp
manifests/role/kubernetes/worker.pp
manifests/role/minimum.pp
spec/classes/all_roles_spec.rb
spec/classes/profile/kubernetes/haproxy_spec.rb
spec/classes/profile/kubernetes/stacked_controller_spec.rb
spec/classes/profile/kubernetes/worker_spec.rb
spec/classes/profile/kubernetes_spec.rb
spec/classes/profile/networking/firewall_spec.rb
spec/classes/role/kubernetes_spec.rb
spec/fixtures/hiera/default.yaml
spec/fixtures/hiera/kubernetes.yaml
spec/fixtures/hiera/kubernetes_config.yaml
templates/profile/kubernetes/haproxy/haproxy.cfg.erb
templates/profile/kubernetes/haproxy/keepalived_post.erb
templates/profile/kubernetes/haproxy/keepalived_pre.erb

Not even a little working yet, but I want Travis to keep an eye on this.

kubernetes

---

manifests/profile/ruby.pp

AEIM-2246 - Install libreadline-dev instead of libreadline6-dev

---

manifests/role/hathitrust/vmhost.pp

See AEim-2293 - eventually we might be able to collapse it -- but just
going to unroll the difference for now.

Add hathitrust::vmhost role

---

lib/puppet/functions/public_ip.rb
manifests/profile/prometheus/exporter/node.pp
spec/functions/public_ip_spec.rb

I have no idea how to test this. I don't think you even can mock facts
in function tests.

AEIM-2253 - EC2 instances know their public IPs

---

manifests/apache/mirlyn_vhost.pp
manifests/profile/www_lib/apache.pp
spec/classes/role/www_lib_vm_spec.rb

add mirlyn defined type, use it in apache profile, bmc.lib.umich.edu for simplicity because it's dead.

add mirlyn/vufind apache vhost

---

manifests/apache/www_lib_vhost.pp
manifests/profile/www_lib/apache.pp
manifests/profile/www_lib/vhosts/staff_lib.pp
spec/classes/role/www_lib_vm_spec.rb

There are a couple of items here that may be useful for other purposes.
In particular, the PHP 5 / mod_php stuff is pretty verbose as well as
arcane. The array / comment / loop helps a little.

AEIM-2207 - Add staff.lib vhost

---

manifests/profile/tools_lib/confluence.pp
manifests/profile/tools_lib/jira.pp
manifests/profile/tools_lib/postgres.pp
manifests/role/tools_lib.pp
spec/classes/profile/tools_lib/postgres_spec.rb

Don't rely on tools specific email key
Rely on new global key
Inherit said key properly (via confluence manifest)

correct tools/postgres email default

---

lib/facter/ruby_versions.rb

Only lists ruby versions managed by rbenv

Add fact to get list of ruby versions

---

manifests/profile/www_lib/vhosts/publishing.pp

Also fixed some indentation issues that Travis was complaining about.

Aeim 2413 purge expired publishing redirects

---

manifests/role/chipmunk.pp

Condition detailed chipmunk/perl deps on OS release

---

manifests/profile/networking/firewall.pp

The stanzas are merged as we discussed.

Refactored to combine ipv4/6 stanzas

---

manifests/profile/elastic/metricbeat.pp
spec/classes/profile/elastic/metricbeat_spec.rb

Stop and disable metricbeat, as we are not using the data.

AEIM-2466 stop and disable metricbeat

---

manifests/profile/hathitrust/ingest_jobs.pp

- jobs are all under bin/jobs
- split out path to perl (with includes) and path to bins

HT-1616: change cron job path for ingest

---

Dockerfile
_dockerignore
docker-compose.yml

- docker-compose run nebula bundle exec rake syntax lint
- docker-compose run nebula bundle exec rake spec
- docker-compose run nebula bundle exec rake spec:prep
- docker-compose run nebula bundle exec rake spec:standalone
- docker-compose run nebula bundle exec rake spec:clean
- docker-compose run nebula bash

AEIM-2525 - Add Docker setup for running test and linter

---

manifests/profile/hathitrust/perl.pp

HT-1997: add libberkeleydb-perl

---

manifests/profile/www_lib/vhosts/redirects.pp

It is trivial but need a quick blessing.

AE-7308 Add AIGA DEC Dialogue redirect to Fulcrum

---

manifests/profile/docker.pp
manifests/profile/kubernetes.pp
manifests/role/hathitrust.pp
manifests/role/hathitrust/prep.pp
manifests/role/hathitrust/prep_app_host.pp
spec/classes/profile/docker_spec.rb
spec/classes/profile/kubernetes_spec.rb

Part of the request was docker-compose, which I figure can be harmlessly
installed anywhere that isn't already serving kubernetes.

AE-7404 - Install docker on sidecar

---

manifests/profile/www_lib/vhosts/redirects.pp

AE-7339 heart_redirect_www-lib

---

manifests/profile/shibboleth.pp
manifests/role/webhost/htvm.pp
manifests/role/webhost/www_lib_vm.pp
spec/classes/role/htvm_webhost_spec.rb
spec/classes/role/www_lib_vm_spec.rb

This approach adds a couple of parameters to the profile and then specifies concrete values in the role. No hiera needed, but possible -- always moving toward open-closed.

AEIM-2640 - Increase shibd timeouts on htvm and www_lib_vm

---

manifests/profile/hathitrust/cron/mdp_misc.pp

configure harvest_proxy_downloads cron

---

templates/profile/prometheus/rules.yml.erb

Alert when windows_update > 30*24*3600 seconds

alert on windows update 30+ days out of date

---

manifests/profile/root_ssh_private_keys.pp
manifests/role/sysadmin_box.pp
spec/classes/profile/root_ssh_private_keys_spec.rb

fetch private ssh keys from puppet-master on bastion hosts

add private keys to bastion hosts

---

manifests/profile/hathitrust/ingest_service.pp

Remove ingest restart job entirely

---

manifests/profile/postfix.pp
manifests/role/umich_mailserver.pp
spec/classes/profile/postfix_spec.rb

Added umich_mailserver role and profiles for postfix on AEIM-1976

---

manifests/profile/apache/authz_umichlib.pp
spec/classes/role/www_lib_vm_spec.rb
spec/fixtures/hiera/www_lib.yaml
templates/profile/apache/sqlnet.ora.erb
templates/profile/apache/tnsnames.ora.erb

- Some additional refactoring to use the newly added variables may be nice to do.
- There are corresponding details in the lot as well.
Extra:
------
Another possible option would be to use https://forge.puppet.com/biemond/oradb but this seems a bit heavy for the minimal client-only settings this needs.

AEIM-2672 Add oracle ora config files and relevant support

---

manifests/apache/redirect_vhost_https.pp

This is done. Please give it a final blessing or comments.

Add missing parameters to http redirection call

---

manifests/profile/www_lib/apache.pp
manifests/profile/www_lib/vhosts/redirects.pp
spec/classes/role/www_lib_vm_spec.rb

Just needs a blessing. Thanks.

Remove beta.lib and bmc.lib redirect

---

manifests/profile/www_lib/vhosts/deepblue.pp

Put Headers in custom fragment to ensure they apply

Fix deepblue cosign issues in www-lib-testing

---

manifests/profile/www_lib/apache.pp
manifests/profile/www_lib/vhosts/apps_lib.pp
manifests/profile/www_lib/vhosts/publishing.pp
manifests/profile/www_lib/vhosts/redirects.pp
manifests/profile/www_lib/vhosts/www_lib.pp
spec/classes/role/www_lib_vm_spec.rb

update.lib, textcreationpartnership, medsearch removed. 
Waiting on confirmation about mblem.

AEIM-2850 delete from www_lib

---

manifests/apache/mirlyn_vhost.pp
manifests/profile/www_lib/vhosts/search.pp

Adding a location stanza to search-http also (before only in https).
Adding NE to mirlyn vhost settings.

AEIM-2857 search lib mirlyn lib adjust

---

manifests/role/app_host/prod_private.pp
spec/fixtures/hiera/default.yaml
spec/fixtures/hiera/www_lib.yaml
templates/profile/apache/authz_umichlib.conf.erb

- Add the www_lib mounts
- Exempt /instruction/request for passive auth

AEIM-2863 - Set up for sali-production on app servers

---

manifests/profile/www_lib/apache.pp
manifests/profile/www_lib/vhosts/midaily.pp

MiDaily vhost has been created but testing is a problem due to the IP mappings. See ticket for details.

AEIM-2861 www lib midaily

---

manifests/profile/www_lib/vhosts/deepblue.pp

Switched to using request_headers and headers

AEIM-1996 Fix new deepblue auth issues

---

manifests/role/webhost/www_lib_vm.pp

Revert "AEIM-2902 - Move www-lib VMs out of testing, into production"

---

manifests/profile/yarn.pp

update key for Apt Repo

---

manifests/profile/www_lib/vhosts/deepblue.pp

Not sure I have the rewrite condition correct.   But its a start.

add rewrite condition and rule to redirect

---

manifests/profile/www_lib/cron.pp

Ae 8571 reschedule cron

---

templates/profile/prometheus/exporter/node/pushgateway.sh.erb

Also clean up the help text and silence curl.

Add custom labels to the pushgateway script

---

manifests/profile/www_lib/php.pp
manifests/profile/www_lib/vhosts/apps_lib.pp

- Add php-oauth package / extension
- Add canvas directory and FPM config

AE-8144 - Canvas / LTI integration support on apps.lib

---

manifests/profile/hathitrust/imgsrv.pp
manifests/role/webhost/htvm.pp

As it was, this seemed to be ignoring settings in hiera

Move the default for number of imgsrv processes to profile

---

templates/profile/prometheus/rules.yml.erb

Increase the DiskAboutToFillUp alert threshold

---

manifests/profile/www_lib/vhosts/deepblue.pp

AE-9671 - Redirect root of deepblue.lib to www.lib

---

manifests/profile/prometheus/exporter/node.pp
templates/profile/prometheus/exporter/node/check_reboot.sh.erb

This is expected to put a bash script into /etc/cron.daily.   That bash script will then generate the prom file and put it in the proper place with the proper value for prometheus to scrape.

add template file and put it in cron.dail

---

manifests/role/webhost/www_lib_vm.pp
spec/classes/role/www_lib_vm_spec.rb

Switching to the updated timeout value as per @skorner.

Switch to shorter startup_timeout value

---

manifests/role/hathitrust/prep_app_host.pp
spec/classes/all_roles_spec.rb
spec/fixtures/hiera/archivematica.yaml
spec/fixtures/hiera/archivematica_config.yaml
spec/fixtures/hiera/default.yaml
spec/fixtures/hiera/quod.yaml
spec/fixtures/hiera/quod_config.yaml

Copied prep_app_host to prep_app_host_tsm.  This new role will be applied to sidecar in order for backups to happen.

create tsm profile specific for sidecar

---

manifests/profile/www_lib/vhosts/apps_lib.pp

We were instructed to create this redirect, but that instruction was in
error.

Stop redirecting human resources

---

Dockerfile
README.md
docker-compose.yml

Also, add docker-compose.yml for local development & update README for
that workflow.

Update bundler & ensure GEM_HOME is set in container

---

manifests/profile/hathitrust/apache.pp

This should expand to the requested:
AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css application/javascript application/xml application/xhtml+xml application/json image/svg+xml
ExpiresActive On
ExpiresDefault "modification plus 2 hours"

HT-3232: Add compression and static cache headers

---

spec/classes/role/www_lib_vm_spec.rb

replaced staff.lib with apps.staff.lib

fix www_lib_vm tests

---

spec/defines/virtual_machine_spec.rb
templates/virtual_machine/bullseye.cfg.erb

Puppet was not starting on new bullseye vms

bullseye preseed: enable puppet w/ late_command

---

manifests/profile/www_lib/vhosts/deepblue.pp

Proxied requests to the apps bypass the general badrobots check for the vhost. Add a RewriteCond to apply badrobots to proxied app requests.

Add badrobots support for Deep Blue Data and Documents

---

manifests/profile/tools_lib/jira.pp

Need more memory. This should have been in hiera, but it's here, and we're turning this off soon.

Increase memory for Jira

---

manifests/role/webhost/htvm.pp
manifests/role/webhost/htvm/site_primary.pp

Install rdist on all htvm hosts

---

manifests/profile/hathitrust/apache/crms_training.pp

Missing crms log dir

---

manifests/profile/hathitrust/perl.pp

Install from CPAN: MARC::Record MARC::File::XML

Add missing MARC support perl modules for HT

---

manifests/profile/www_lib/apache/base.pp
manifests/profile/www_lib/dependencies.pp
manifests/profile/www_lib/perl.pp
manifests/profile/www_lib/vhosts/press.pp
manifests/profile/www_lib/vhosts/www_lib.pp
manifests/role/webhost/fulcrum_www_and_app.pp
manifests/role/webhost/www_lib_vm.pp

The changes are limited to what was necessary for bullseye compatibility plus some cleanup that made sense to include in one PR. I split the cleanup work into a separate commit.

Update general web hosting role/profile for Debian 11 (bullseye) compatibility

---

manifests/profile/fulcrum/app.pp
manifests/profile/monitor_pl.pp
manifests/profile/ruby.pp
manifests/profile/solr.pp
manifests/profile/www_lib/apache/base.pp
manifests/profile/www_lib/dependencies.pp
manifests/profile/www_lib/perl.pp
manifests/role/webhost/fulcrum_www_and_app.pp
spec/fixtures/hiera/default.yaml
spec/fixtures/hiera/fulcrum.yaml
spec/fixtures/hiera/www_lib.yaml

This way, it can be mounted before the app is deployed.

Upgrade fulcrum VMs to bullseye

---

manifests/profile/www_lib/apache/fulcrum.pp
manifests/profile/www_lib/vhosts/publishing.pp

Removed the redirects from this request:
https://teamdynamix.umich.edu/TDNext/Apps/87/Tickets/TicketDet?TicketID=3468824

remove redirects per TDX 3468824

---

manifests/profile/hathitrust/apache.pp
manifests/profile/hathitrust/apache/babel.pp
manifests/profile/hathitrust/apache/matomo.pp
spec/fixtures/hiera/hathitrust.yaml

* add vhost/subdomain for matomo to ht apache config
* move client cert to top level ht apache config

DEV-672: proxy ht matomo with apache

---

manifests/profile/http_fileserver.pp

delete unused var in http_fileserver

---

.fixtures.yml
metadata.json

missed these in the previous clean-up PR

Delete dependencies for atlassian tools

---

manifests/profile/openjdk_java.pp
manifests/role/app_host/prod_private_java.pp
manifests/role/hathitrust/solr/indexing.pp

Creating a pull request to revisit this and discuss what else would need to be done.

Manage openjdk java

---

manifests/profile/fulcrum/symlinks.pp
manifests/role/fulcrum/app_host.pp

to adapt to new mistorage not allowing deep mounts

Add symlink support to role::fulcrum::app_host

---

manifests/profile/kubernetes/apt.pp
manifests/profile/kubernetes/kubeadm.pp
manifests/profile/kubernetes/kubeadm_config.pp
manifests/profile/kubernetes/kubelet.pp
spec/classes/profile/kubelet_spec.rb
spec/classes/profile/kubernetes/kubeadm_spec.rb
spec/classes/profile/kubernetes/kubelet_spec.rb
spec/fixtures/hiera/kubernetes/default.yaml

https://kubernetes.io/blog/2023/08/15/pkgs-k8s-io-introduction/

kubernetes apt repos moved

---

manifests/profile/aleph/perl.pp

These were added by hand after the upgrade to bullseye.

add cpan modules

---

.fixtures.yml
manifests/profile/apt.pp
metadata.json

- remove unused puppetlabs/java module
- add apt repo for adoptium/temurin
- copied from https://github.com/mlibrary/nebula/pull/642/commits/61e6e2279d94a02a3d0e53d74e444be33111f6ae (did not cherry-pick because this wasn't the only file changed on that commit)

Adoptium java

---

manifests/profile/www_lib/vhosts/apps_lib.pp

I think this is what albert is asking for.  in the TDX ticket.

update sali1 to sali

---

manifests/log.pp
manifests/profile/hathitrust/apache.pp
manifests/profile/hathitrust/solr6/catalog.pp
manifests/profile/hathitrust/solr6/classic.pp
manifests/profile/loki.pp
manifests/role/hathitrust/prod.pp
manifests/role/hathitrust/prod/app_host.pp
spec/classes/profile/hathitrust/apache_spec.rb
spec/classes/profile/hathitrust/solr6/catalog_spec.rb
spec/classes/profile/hathitrust/solr6/classic_spec.rb
spec/classes/profile/loki_spec.rb
spec/defines/log_spec.rb
spec/fixtures/hiera/hathitrust.yaml
templates/profile/loki/alloy.env.erb
templates/profile/loki/config.alloy.erb
templates/profile/loki/drop_in.alloy.erb

- install and configure grafana-agent
- add grafana-agent profile to solr6::catalog profile
- planning to also add this to the solr6::lss profile before squashing and merging

grafana alloy profile
