mlibrary/nebula

- .rspec
This reverts commit e17a35fddd6b4ad7d6d14662dabab4b84ae00ad0.
It turns out that when a pattern is supplied in this way, the rspec
executable ignores when you specify a single file, and will thus
always run the full suite. This is undesireable.
> Revert "Make 'rspec' do what 'rake spec_standlone' does"

- .rubocop.yml
- lib/puppet/functions/fact_for.rb
- lib/puppet/functions/nodes_for_datacenter.rb
- lib/puppet/functions/nodes_for_role.rb
- spec/functions/fact_for_spec.rb
- spec/functions/nodes_for_datacenter_spec.rb
- spec/functions/nodes_for_role_spec.rb
They mock puppetdb so that you don't have to. You can just mock these
functions instead. I tested that puppetdb_query works the way I'm
assuming it does by checking by hand in production, adding lines like
this one to site.pp:
notify { to_json(puppetdb_query([etc])): }
Then I ran puppet agent on one of the other nodes to see if it returned
the output I expected. I am confident that these functions can be
trusted to work right when in production.
> AEIM-1244: Add functions for getting facts for other nodes

- data/common.yaml
- manifests/authzd_user.pp
- manifests/profile/haproxy.pp
- spec/classes/profile/haproxy_spec.rb
- spec/defines/authzd_user_spec.rb
- spec/defines/file/ssh_keys_spec.rb
- templates/file/ssh_keys.erb
Things I'd like feedback on:
- Whether the method of passing the user to the haproxy profile looks reasonable
- The nebula::authzd_user define in general - the general existence of it, but also in particular if there's a way of passing excess parameters to the user resource, that'd be nice (i.e. basically have nebula::authzd_user act as a decorator that ensures the home directory exists and can provision an ssh key in addition to actually creating the user)
- If there's a cleaner way of passing the parameters from `nebula::profile::haproxy` to `nebula::authzd_user` (a la https://github.com/mlibrary/nebula/blob/master/manifests/profile/vmhost/host.pp#L30 ) (I might experiment a little bit here if I have time)
- An easier-to-read way than …
> provision user for monitoring haproxy

- data/common.yaml
- manifests/profile/haproxy.pp
- manifests/profile/haproxy/keepalived.pp
- spec/classes/profile/haproxy/keepalived_spec.rb
- spec/classes/profile/haproxy_spec.rb
- templates/profile/haproxy/frontends.cfg.erb
- templates/profile/haproxy/keepalived/keepalived.conf.erb
* Changes floating_ip from a single string to a hash based on service name
* Remove all vestiges of fixed service name 'www-lib'
* Use correct SSL cert dir based on service name
N.B. I manually tested the syntax for keepalived (multiple floating IPs in a single virtual_ipaddress block) and it seems to work AFAICT
> AEIM-1248: support multiple floating IPs

- manifests/profile/haproxy/keepalived.pp
- spec/classes/profile/haproxy/keepalived_spec.rb
- templates/profile/haproxy/keepalived/keepalived.conf.erb
partially reverts https://github.com/mlibrary/nebula/commit/53e3bd8b#diff-6587d3550c955340798dee887ef692b5R36
> only use other keepalive nodes as keepalived "unicast peers"

- .fixtures.yml
- manifests/profile/vmhost/host.pp
- metadata.json
- spec/classes/profile/vmhost/host_spec.rb
I figure we can factor the LV / filesystem / mount creation out to a new define the next time we want to do it the same way.
> optionally provisions local storage for a vmhost

- data/common.yaml
- manifests/profile/haproxy.pp
- spec/classes/profile/haproxy_spec.rb
allows us to use deep merge strategy in hiera - not making that the
default here though
> remove default services/floating ips for haproxy

- manifests/haproxy_service.pp
- spec/defines/haproxy_service_spec.rb
- templates/profile/haproxy/service.cfg.erb
- use absolute path (haproxy wasn't finding it)
- accept as many whitelists as we want
- name whitelists according to haproxy match type (path_beg, path_end,
etc)
> use correct acl syntax for whitelists

- manifests/haproxy_service.pp
- spec/defines/haproxy_service_spec.rb
- templates/profile/haproxy/service.cfg.erb
This addresses a couple major issues with the behavior of whitelisted
paths in the previous design that are counter to how throttling
works in the NetScaler implementation:
- If you requested only whitelisted paths, they still incremented the
requst rate. So, if you limited most requests to for example 10 requests
per second, and you did 20 requests to whitelisted paths in one second,
the next request to a non-whitelisted path would get throttled.
- With the temporary ban list in the front end but the whitelists in the
back end, once you had gone over the request rate ALL requests to the
front-end would be denied, even those for whitelisted paths.
Now:
- Throttling only checks the average request rate in the backend -
there's no longer any blocking in the front end (we could bring that …
> AEIM-1293: rewrite throttling & whitelisting

- data/common.yaml
- manifests/named_instance.pp
- manifests/profile/named_instances.pp
- manifests/profile/named_instances/puma_wrapper.pp
- spec/classes/profile/named_instances_spec.rb
- spec/defines/named_instance_spec.rb
- templates/named_instance/puma.service.erb
- templates/profile/named_instances/puma_wrapper/script.erb
Resolves AEIM-1156
This adds a wrapper over puma that can handle applications with legacy
or modern deployments. This should aid in migrating those deployments.
The possible scenarios are (in order of how common they are):
This solution addresses all of these scenarios. Those that have been tested on live servers are checked off.
> Add puma wrapper to profile::named_instances

- lib/facter/network_cards.rb
- manifests/profile/base.pp
- manifests/profile/base/i40e.pp
- spec/classes/profile/base_spec.rb
The default driver that comes with Debian Stretch is not stable. See JIRA issue and commit messages for more details.
> AEIM-1502: install i40e-dkms if intel x710 network card is installed

- .fixtures.yml
- manifests/profile/hathitrust/php.pp
- metadata.json
- spec/classes/role/htvm_webhost_spec.rb
This attempts to install all of the PEAR modules through the
'puppet/php' module, which appears to be the most mature and maintained
on the forge. The usage does not install FPM, dev headers, or composer,
but each is simple to add. I chose to remove the Debian packages for the
select few PEAR modules and list them all as extensions on the PHP
resource.
> AEIM-1430 - Install PEAR modules with puppet/php

- manifests/profile/hathitrust/apache.pp
- spec/classes/profile/hathitrust/apache_spec.rb
- spec/fixtures/hiera/hathitrust.yaml
The approach used here does not add another parameter to the Apache
profile, but I would not be opposed to doing so. This commit does an
explicit lookup in hiera. The fixture data includes a model for mapping
networks in multiple places without repeating the actual data, using
alias interpolation.
> AEIM-1628 - Look up staff networks for mod_status

- manifests/profile/hathitrust/apache.pp
- spec/classes/profile/hathitrust/apache_spec.rb
This sets all of the SSL vhosts to use only ECDHE-RSA-AES256-GCM-SHA384
and explicitly sets only TLSv1, 1.1, 1.2 for the protocol. The HAProxy
config already supports this cipher, so no changes are needed there.
> AEIM-1661 - Set strict cipher suite for HT web nodes

- manifests/profile/geoip.pp
- manifests/profile/hathitrust/apache.pp
- manifests/profile/hathitrust/imgsrv.pp
- manifests/profile/hathitrust/shibboleth.pp
Resolves AEIM-1633
This PR is based on aeim-1426/common_crons, as it must be complete in order for that PR to be viable.
This adds the five files described in the commit subjects to their respective profiles. The files are downloaded from ae-files, where they have been uploaded via ae-utils--see that git project for an exact list.
The files were added to /usr/local/bin as we intend /l/local/bin to be a symlink to that directory. Leaving /l/local/bin out of the picture for this issue prevents any race conditions that would need to be resolved via dependency.
See the JIRA for why some files were excluded from this PR.
> Add bins from /l/local/bin to /usr/local/bin

- manifests/profile/geoip.pp
- manifests/profile/hathitrust/apache.pp
- manifests/profile/hathitrust/apache/babel.pp
- manifests/profile/hathitrust/apache/catalog.pp
- manifests/profile/hathitrust/apache/logs.pp
- manifests/profile/hathitrust/apache/statistics.pp
- manifests/profile/hathitrust/apache/test.pp
- manifests/profile/hathitrust/apache/www.pp
- manifests/profile/hathitrust/imgsrv.pp
- manifests/profile/hathitrust/shibboleth.pp
- manifests/role/webhost/htvm/prod.pp
- manifests/role/webhost/htvm/prod/primary.pp
- manifests/role/webhost/htvm/test.pp
Resolves AEIM-1426
This adds the existing cron jobs from our Hathitrust web servers, both common and not-so-common.
Adding the cron tasks themselves was straightforward. The complexity arose from choosing where they should go. In the end, I chose to focus on putting the tasks in the profiles to which they belong. This resulted in a couple new sub-profiles, and some new sub-roles.
It is the topography of the roles-profiles-crontasks that is most in need of review.
See [here](https://tools.lib.umich.edu/jira/secure/attachment/57434/tabs.txt) for a summary of the cron jobs as they existed on our servers, the profile in which they ended up, and the most general role that includes said profile.
> Add cron jobs

- manifests/profile/hathitrust/apache.pp
- spec/classes/profile/hathitrust/apache_spec.rb
- templates/profile/apache/logrotate.d/apache2.erb
- Add a static template for the config
- Add a File using the template for HT Apache profile
This is a provisional directory structure. We don't yet have a base
Apache profile, but I expect one soon. It wasn't obvious whether this
was more of an Apache concern or a logrotate concern, but it seems more
on the Apache side.
> AEIM-1672 - Add log rotation for Apache

- manifests/role/hathitrust/ingest_indexing.pp
- spec/classes/role/ht_ingest_spec.rb
This adds a simple role for ingest in one commit. It depends on the cleanup happening for AEIM-1449. Once that is merged, this should be rebased to master. It should be considered blocked for now.
> AEIM-1453 - Add ingest role

- manifests/profile/networking/firewall/http_datacenters.pp
- manifests/profile/networking/firewall/ssh.pp
- spec/classes/profile/networking/firewall/http_datacenters_spec.rb
- spec/classes/profile/networking/firewall/ssh_spec.rb
Naming was a little bit different between firewall and mod_status stuff
- whether the block was called 'block' or 'source'.
Now, the parameter name is 'networks', and each "network" should have a 'name',
'block', and optional 'datacenter' key.
> Make expected naming for IP blocks consistent

- manifests/profile/apt/testing.pp
- manifests/profile/hathitrust/dependencies/ingest_indexing.pp
- manifests/role/hathitrust/ingest_indexing.pp
Installs jhove (specifically from buster if we're on Debian 9) and openjdk-8-headless. 
Use of 'testing' for apt repo and 'buster' for jhove prioritization are each intentional as this will not break when we upgrade to buster, and provides a reusable profile to add testing repo for any future pinning needs.
> install jhove on hathitrust ingest from debian testing

- manifests/profile/dns/smartconnect.pp
- manifests/profile/hathitrust/mounts.pp
- spec/classes/role/htvm_webhost_spec.rb
Although tests for Class[resolv_conf] passed, in reality it gives the
error:
Error 500 on SERVER: Server Error: Invalid relationship: Mount[/htapps]
{ require => Class[resolv_conf] }, because Class[resolv_conf] doesn't
seem to be in the catalog
This changes it to depend on File[/etc/resolv.conf] instead, which also
has the benefit that it won't break if we generate resolv.conf directly
instead of using the (potentially dubious) resolv_conf forge module.
> AEIM-1629: make smartconnect depend on /etc/resolv.conf

- manifests/profile/networking/firewall.pp
- spec/classes/profile/firewall_spec.rb
- spec/fixtures/hiera/firewall.yaml
- spec/fixtures/hiera/firewall_config.yaml
Defaults are tcp, NEW, and 'accept', but hiera can override them
> AEIM-1646: Support firewall resources in hiera

- manifests/profile/dns/aws.pp
- manifests/role/aws.pp
- spec/classes/profile/dns/aws_spec.rb
For AWS hosts, EC2 service sets correct DNS via DHCP. Keep this, but override the search domain in dhclient.conf. Restarts networking, it's coarse, but I couldn't find anything cleaner (dhclient -r only looks for a new lease, doesn't appear to reload the config).
> AWS: Set search domain via dhclient, don't set dns servers

- manifests/profile/puppet/master.pp
- spec/classes/profile/puppet/master_spec.rb
- spec/fixtures/hiera/default.yaml
It's currently pointing at a symlink, which it refuses to tidy. This way
it can point at the actually directory, and /var can stop filling up.
> AEIM-1707 - Specify puppet's reports directory

- .fixtures.yml
- manifests/nfs_mount.pp
- manifests/profile/dns/smartconnect.pp
- manifests/profile/hathitrust/apache/default.pp
- manifests/profile/hathitrust/mounts.pp
- manifests/profile/monitor_pl.pp
- manifests/role/hathitrust/ingest_indexing.pp
- metadata.json
- spec/classes/profile/hathitrust/apache_spec.rb
- spec/classes/profile/hathitrust/mounts_spec.rb
- spec/classes/profile/monitor_pl_spec.rb
- spec/classes/role/ht_ingest_spec.rb
- spec/classes/role/htvm_webhost_spec.rb
- spec/fixtures/hiera/hathitrust.yaml
monitor_pl class is generic and can be re-used by other web servers when we puppetize those.
This uses `concat` resources with the `yaml` format to generate the monitor config out of multiple resources that are specified in the same place as the `mount` resources rather than with the monitor. It could easily be extended to use exported resources for the solr & mysql monitoring in the future.
This is supported by changes in ae-utils (a version of monitor.pl that works with the stripped-down config generated here) and in lensoftruth (parameters for monitoring solr & mysql).
> AEIM-1651: configure monitor.pl for HT web servers; nfs_mount defined type

- manifests/profile/hathitrust/dependencies/ingest_indexing.pp
- spec/classes/role/ht_ingest_spec.rb
buster version of jhove now pins to some dependencies that are only in
buster; see debian changelog for jhove 1.20.1-5:
https://metadata.ftp-master.debian.org/changelogs/non-free/j/jhove/jhove_1.20.1-5_changelog
> AEIM-1773: pin deps for jhove

- manifests/profile/hathitrust/dependencies/ingest_indexing.pp
latest build of jhove requires openjdk 11
> install openjdk 11 instead of openjdk 8 for ht ingest machines

- .gitignore
- manifests/named_instance.pp
- manifests/profile/named_instances.pp
- manifests/proxied_app.pp
- manifests/role/sysadmin_box.pp
- spec/classes/profile/named_instances_spec.rb
- spec/defines/named_instance_spec.rb
- spec/spec_helper.rb
- templates/profile/apache/proxy_vhost.erb
This introduces a new resource type to be exported by the named instance
and collected by the appropriate web servers. There are definitely some
rough edges, like the number of values that are shuttled along between
the components, but it's a good start. The template is ported almost
verbatim from ansible-predeploy, with the exception being that the
"extra config" is pruned in favor of "sendfile_path", the one feature of
the inlined config that has been used so far. If we need to model
instances more richly, we can do that, but I hesitate to preserve a
literal expansion from hiera.
The instances in lens will need a number of new keys for this to work.
> [WIP] AEIM-1760 - Export instances for Apache configuration

- manifests/haproxy/binding.pp
- manifests/role/webhost/htvm.pp
- spec/classes/role/htvm_webhost_spec.rb
- spec/defines/haproxy_binding_spec.rb
Implements https_offload: false case for haproxy to apache binding for
the new HT web server role where apache and haproxy both terminate ssl
> AEIM-1772: Bind htvm web hosts to haproxy

- .fixtures.yml
- manifests/named_instance.pp
- manifests/profile/named_instances.pp
- metadata.json
- spec/classes/profile/named_instances_spec.rb
- spec/defines/named_instance_spec.rb
- Creates the user and the database with the puppetlabs mysql module, running on (at least one of) the hosts that the app is deployed on
- Assumes that credentials that can connect to the database and create users are in `/root/.my.cnf` on the app server (puppetlabs-mysql assumption)
- Database is only created if user/password parameters are given and create_database is true.
> AEIM-1758: configure databases for moku-deployed apps via puppet

- manifests/named_instance.pp
- manifests/named_instance/solr_core.pp
- spec/defines/named_instance_spec.rb
- spec/defines/solr_core_spec.rb
- spec/fixtures/hiera/default.yaml
Creare dummy "release 0" for each named instance
If there isn't a released version yet, link this one and init the solr core
> Initialize solr core for new named instance

- .fixtures.yml
- manifests/profile/ntp.pp
- metadata.json
- spec/classes/profile/ntp_spec.rb
changing ntp servers with file_line or using multiple ntp servers didn't
work very well
this should generate an ntp config that is similar to the debian defaults + using our servers except for collection of statistics that we don't use anyway
> use puppetlabs-ntp

- manifests/profile/nodejs.pp
- manifests/role/app_host/dev.pp
- manifests/role/app_host/prod.pp
- manifests/role/deploy_host.pp
* Adds the nodejs profile
* Adds the profile to the app_host:dev, app_host:prod, and deploy_host roles
We abstain from including tests here because the data is static, and any tests would likely be brittle.
> Add nodejs to app_host and deploy_host

- manifests/profile/ruby.pp
This adds a number of system packages that are commonly required by ruby gems that build native extensions.
These are all system packages I've required at some point or another. Unfortunately, I don't have the mappings of what required them.  At the very least, we should include libsqlite3-dev.
> Include system packages commonly required by ruby

- manifests/named_instance.pp
- spec/defines/named_instance_spec.rb
We had assumed a false equivalency between moku's `systemd_services` and puppet's systemd `subservices`. It turns out that given our current strategy, moku always just needs `instance-name.target` only.
> Export moku systemd_services correctly

- Gemfile.lock
- manifests/profile/ruby.pp
- spec/classes/profile/ruby_spec.rb
- spec/fixtures/hiera/default.yaml
* Adds $bundler_version parameter to profile::ruby
* Gems are now specified as an array of hashes. The hashes two elements `gem` and `version`. The default behavior of the rbenv module for version is to use `>= 0`
* Makes appropriate changes in the fixtures and specs for above
This requires a corresponding change in hiera. I have that ready to push.
~~Also, this PR cannot be made to work in travis, as travis no longer wants to accept bundler before 2.x. If we made that change here, we'd never be able to run puppet to apply it to our serves. Chicken and egg.~~
> Install bundler 2.x as well as 1.x

- manifests/profile/hathitrust/perl.pp
The previous attempt for this used DBD::Mem, but that module is only available in newer distributions of DBI than what is provided in stretch.
This is a consequence of how the single image validator is tied in to the rest of the ingest code - it still opens a database connection even though it never uses it.
> HTREPO-179: add libdbd-mock-perl

- templates/virtual_machine/stretch.cfg.erb
Remove our complex partition scheme for VMs and just make one partition. Also eliminates swap.
> Make only one partition on new VMs

- manifests/named_instance/proxy.pp
- spec/defines/named_instance/proxy_spec.rb
I feel like `/sysadmin/archive` would be better represented as a thing of its own profile and/or something in hiera, but neither is currently needed by anything, and both add complications that I'm not inclined to get into.
> AEIM-2027 - Ensure required parent directories exist

- manifests/profile/apt.pp
- spec/classes/profile/apt_spec.rb
It looks like the issue with our local apt repo is that it doesn't have any i386 packages, and for some reason apt expects those to exist even when run on an amd64 computer? Adding `[arch=amd64]` to the sources.list does fix the problem, and this is the code that should add that to the sources.list, although I had to look at the apt module source to be sure, and it's possible we'll need to upgrade to a newer apt module version, but this should prevent apt from trying to grab i386 binaries.
> AEIM-2028 - Add architecture to the local apt source

- manifests/named_instance/app.pp
- spec/defines/named_instance/app_spec.rb
When a named_instance::app should be deployed to the app user's home
directory, do not create a separate file resource.
> AEIM-2055 - Don't create separate directory for app

- manifests/named_instance/app.pp
- spec/defines/named_instance/app_spec.rb
This addresses a problem with the home directory being group writeable.
It also goes back to the notion that we can remove setgid and group
write for the rest of the dirs. It did not end up simplifying to
preserve the 2775.
> AEIM-2055 - Second pass to fix directory modes

- files/pg_backup
- manifests/profile/tools_lib/confluence.pp
- manifests/profile/tools_lib/jira.pp
- manifests/profile/tools_lib/postgres.pp
- manifests/role/tools_lib.pp
- spec/classes/profile/tools_lib/confluence_spec.rb
- spec/classes/profile/tools_lib/jira_spec.rb
- spec/classes/profile/tools_lib/postgres_spec.rb
- spec/fixtures/hiera/tools_lib.yaml
Adds some documentation to the tools_lib profiles as well.
Moves the includes for postgres & jdk to the confluence & jira profiles,
so that we can test those profiles without the need for a preamble.
> AEIM-1928: cron jobs for atlassian backups

- manifests/profile/tools_lib/apache.pp
Set nocanon so apache doesn't mangle confluence URLs
> AEIM-2094 set nocanon for proxy_pass on tools_lib

- metadata.json
There is some dependency conflict with the recent 6.0.0 release of
puppetlabs/postgresql. We did not have an upper bound on our dependency
in metadata.json, and it appears that the Puppetfile.lock did pick up a
hard major version block, so librarian puppet was failing.
> AEIM-2094 - Put upper bound on puppetlabs/postgresql

- lib/puppet/functions/nodes_for_class.rb
- spec/functions/nodes_for_class_spec.rb
This should keep anything that relies on the output of nodes_for_class
from seeing arbitrary changes in catalogs based on ordering.
> AEIM-2097: sort the results of nodes_for_class

- manifests/haproxy/service.pp
- spec/defines/haproxy_service_spec.rb
This could easily be extended to a hash of custom error pages per
service should that become necessary at some point in the future.
> AE-4510: support custom 503 error per service

- manifests/role/aleph/marcedit.pp
- manifests/role/app_host/dev.pp
- manifests/role/umich.pp
- spec/classes/role/aleph_marcedit_spec.rb
- spec/classes/role/app_host_dev_spec.rb
- spec/classes/role/htvm_webhost_spec.rb
- spec/classes/role/umich_spec.rb
- spec/classes/role/vmhost_spec.rb
- AFS and human users were not installed via puppet on Debian 8 hosts
anyway
- Puppet won't automatically remove AFS & human users anywhere, just not add them in the future to nodes with that role, so we can control the deprovisioning
- This does keep AFS & human users on ht dev mysql for now, where it is not really needed (by virtue of inclusion of AFS & human users on all HT hosts) but we can/should adjust that when that role is fully puppetized.
> AEIM-1897: Restrict AFS and human users to roles that need it

- manifests/profile/haproxy.pp
- spec/classes/profile/haproxy_spec.rb
- templates/profile/haproxy/keepalived/keepalived_pre.erb
This way, we can experiment with alternative HAProxy configurations
before we codify them into puppet formally. Puppet has to manage the
floating IPs because it manages the keepalived config file already.
Without this commit, the only way to get keepalived to bind a floating
IP address was to set up an HAProxy HTTP/S service, which isn't always
what's needed. In the long term, this parameter should be considered a
smell, since it implies some hand-crafted HAProxy configuration that has
yet to be folded into puppet.
> AEIM-2146 - Allow keepalived to bind non-haproxy IPs

- templates/virtual_machine/stretch.cfg.erb
This was causing an error message to appear when creating vms anytime uchicago was down, which doesn't break anything, but it does require manual intervention, so I've switched it to the generic mirror.
> Use ftp.us.debian.org instead of debian.uchicago.edu

- manifests/profile/geoip.pp
- manifests/profile/hathitrust/dependencies.pp
- spec/classes/role/chipmunk_spec.rb
adds default parameters for geoip username & license key so it can be
installed but (effectively) unconfigured. the alternative would be
setting it in the specs in hiera, but it makes no sense to force a hiera
configuration for a component we don't even use for chipmunk. longer
term it would be better to include only the dependencies we actually
need for feed.
> PFDR-178: get chipmunk role working

- manifests/profile/mysql.pp
- manifests/profile/redis.pp
- manifests/role/chipmunk.pp
- spec/classes/profile/mysql_spec.rb
- spec/classes/profile/redis_spec.rb
- spec/default_facts.yml
Adds a profile for each of mysql and redis, and adds them to the app_host::dev and app_host::prod roles only.
> Pfdr 225/mysql redis

- manifests/profile/afs.pp
- manifests/profile/networking.pp
- manifests/profile/networking/sshd.pp
- manifests/role/aws.pp
- manifests/role/hathitrust.pp
- manifests/role/umich.pp
- spec/classes/profile/networking/sshd_spec.rb
- spec/classes/profile/networking_spec.rb
On Ubuntu, there are ssh errors with the GSSAPI authentication method if
the keytab file isn't actually there, and in general advertising that
method only leads to confusion if it doesn't actually work.
This change:
- always includes the keytab profile (it is a no-op if there is no
actual keytab file to install)
- only sets GSSAPIAuthentication Yes if the keytab profile installed a
keytab
> AEIM-2180: set GSSAPIAuthenticationYes only if keytab file exists

- manifests/profile/named_instances/apache.pp
- manifests/role/app_host/standalone.pp
- manifests/role/chipmunk.pp
- spec/classes/role/chipmunk_spec.rb
- spec/fixtures/hiera/chipmunk.yaml
- Doesn't deploy any vhost config; you still need to manually put it in place
- Breaks up standalone apache / app server and chipmunk-specific stuff
> AEIM-2162 / PFDR-178: configuration for standalone apache server

- manifests/profile/duo.pp
- manifests/profile/networking/firewall.pp
- spec/classes/profile/networking/firewall_spec.rb
- Removes old duo package & declaration in pam.d
- Ensures that packages that would have been installed on a fresh stretch machine are present (and removes lokkit)
Because it uses `ensure => absent` rather than `ensure => purge`, the config files for duo and lokkit will be left in place so that settings can be migrated if necessary.
> Apply necessary updates for migrating from jessie to stretch

- lib/puppet/functions/lookup_role.rb
- manifests/profile/prometheus.pp
- manifests/profile/prometheus/exporter/node.pp
- manifests/role/minimum.pp
- manifests/role/prometheus.pp
- spec/classes/profile/prometheus/exporter/node_spec.rb
- spec/classes/profile/prometheus_spec.rb
- spec/fixtures/hiera/default.yaml
- spec/fixtures/hiera/role_is_aws_auto.yaml
- spec/fixtures/hiera/role_is_aws_auto_config.yaml
- spec/fixtures/hiera/role_is_my_role.yaml
- spec/fixtures/hiera/role_is_my_role_config.yaml
- spec/functions/lookup_role_spec.rb
- templates/profile/prometheus/config.yml.erb
- templates/profile/prometheus/exporter/node.sh.erb
- templates/profile/prometheus/rules.yml.erb
This will affect every non-jessie node we have (that's being managed by puppet at least). This will run `apt-get install prometheus-node-exporter` and will open a port to the Prometheus server at its datacenter (if there is one).
Other than that, the purpose here is to set us up with a Prometheus server at each datacenter, with every node giving it basic hardware monitoring data.
Out of scope is setting up the alert manager and figuring out how best to aggregate everything into such as a pretty dashboard. The alert manager and dashboards are pieces of this that I think would fit well in kubernetes (as well as monitoring other details such as Apache)—but the basic hardware monitoring is definitely easiest to set up through puppet.
> Prometheus plus node exporters

- manifests/profile/aws/filesystem.pp
This is particularly a problem on machines where partitions exist on
xvdb, because then puppet honks up the mounts by trying to mount xvdb,
when xvdb1 is already mounted...
> Allow configuration of the device for AWS filesystem

- manifests/role/app_host/dev_private.pp
Continues to point to the need for dependency injection based on data
from hiera
trivial PR based on production app host with private networking
> Mashup dev app host with private networking

- manifests/named_instance.pp
- spec/defines/named_instance_spec.rb
- templates/named_instance/puma.service.erb
This is a better default than localhost for most of our configurations,
allowing separate web and app server nodes with less messing around
after the fact.
> AEIM-2328 - Default puma bind address to all interfaces

- manifests/profile/apt.pp
The packages don't clash with the Debian openjdk packages, so this should be safe to add everywhere.
At least on jessie, we will probably want to use the adoptopenjdk8 package rather than the (no longer maintained) openjdk8 from backports.
> Add adoptopenjdk repository everywhere

- files/tsm/tsm.service
- manifests/profile/tsm.pp
- manifests/role/hathitrust/backup.pp
- spec/classes/profile/tsm_spec.rb
- spec/classes/role/ht_backup_spec.rb
- spec/fixtures/hiera/hathitrust.yaml
- templates/profile/tsm/dsm.opt.erb
- templates/profile/tsm/dsm.sys.erb
Specifically for HT backup servers.
How to include the TSM profile for other nodes running TSM is out of scope for this PR.
> AEIM-1663: Configure TSM via puppet

- manifests/profile/php73.pp
- manifests/profile/www_lib/apache.pp
- manifests/profile/www_lib/php.pp
- spec/classes/profile/www_lib/php_spec.rb
Applies our config changes for fpm's config.ini. We're already installing the php fpm daemon in php73.pp, so no action required there. 
Also fix a regression w/ BMC vhost (missing apache log dir)
> AEIM-2313 php

- manifests/profile/hathitrust/ingest_jobs.pp
Some of the cron jobs expect to have the mailx from RHEL, which is known as 'heirloom-mailx' on Debian. It provides some different command line flags and features including being able to attach a file.
> Add heirloom-mailx package

- manifests/profile/tools_lib/postgres.pp
- manifests/role/tools_lib.pp
- spec/classes/role/tools_lib_spec.rb
- spec/fixtures/hiera/default.yaml
There were two small problems popping up when running on a new AWS VM
provisioned with this role tag:
1. The mail_recipient had no default value, so we needed a node file
2. The postgres profile didn't have sufficient dependency information
on the backup directories
This change introduces a nebula::automation_email to parallel root_email
and a few requires to ensure that postgres is installed before the
backup directories and cron entry are managed.
With a mail_recipient value in common.yml, these hosts can be
provisioned with only an AWS tag.
> AEIM-2242 - Fix up tools_lib to succeed on first run

- manifests/profile/hathitrust/apache/catalog.pp
puppet doesn't complain, just silently omits the `<FilesMatch>` if the parameter name is wrong :(
> AEIM-2345: correct "location" to "path"

- Gemfile.lock
For some reason, running specs was updating the Gemfile.lock, resulting
in frequent, uncommitted changes. This just commits what everybody is
ending up with on each test run, outside of any functional change.
> Update Gemfile.lock fully

- lib/facter/prometheus_errors_total.rb
- manifests/profile/named_instances.pp
- manifests/profile/prometheus/exporter/node.pp
- manifests/profile/rsyslog.pp
- manifests/subscriber/rsyslog.pp
- manifests/subscriber/systemctl_daemon_reload.pp
- spec/classes/profile/prometheus/exporter/node_spec.rb
- spec/default_facts.yml
- templates/profile/prometheus/exporter/node/node_exporter_errors.prom.erb
- templates/profile/prometheus/exporter/node/rsyslog.conf.erb
- templates/profile/prometheus/exporter/node/systemd.ini.erb
Sometimes the prometheus node exporter has errors, and those errors fill
up /var/log. This way, they'll be cleared out every 30 minutes, but also
their presence won't be lost.
> Delete prometheus logs but expose error count

- manifests/apache/www_lib_vhost.pp
- manifests/profile/www_lib/apache.pp
- manifests/profile/www_lib/vhosts/press.pp
- spec/classes/role/www_lib_vm_spec.rb
- templates/profile/www_lib/vhosts/press/press.service.erb
- templates/profile/www_lib/vhosts/press/startup_press.erb
Other than adding a `setenv` parameter to `nebula::apache::www_lib_vhost`, this doesn't much modify anything that already exists.
> AEIM-2205 - Add vhost for www.press.umich.edu

- manifests/profile/www_lib/php.pp
The PHP settings are duplicated across 5 and 7 for now; we can find a
better way to normalize them later.
> AEIM-2313 - Restore settings for mod_php

- manifests/apache/redirect_vhost_http.pp
- manifests/apache/redirect_vhost_https.pp
- manifests/apache/www_lib_vhost.pp
- manifests/profile/www_lib/apache.pp
- manifests/profile/www_lib/vhosts/redirects.pp
- spec/classes/role/www_lib_vm_spec.rb
Implements the "redirects vhost" in puppet. Some notes:
* This terminates ssl for those vhosts that were specified as https. This is a change from what was in rdist. See Aaron's comments on #198 
* https redirects automatically have http redirects as well
* The `copyright` redirects have been removed; copyright dept (group?) confirms they're not currently being used anyway, and gave the greenlight to remove them so long as there was no risk of content loss.
> AEIM-2206: Create redirects vhost

- manifests/profile/www_lib/vhosts/openmich.pp
We were including `lib` in the role, giving openmich.www.lib.lib as an alias.
> AEIM-2409 - Fix up Open Michigan ServerAlias

- manifests/profile/networking/firewall.pp
This should make the rules.v6 file block all ipv6 traffic by making chains empty and default to drop.
> Block IPv6: purge chains and default to drop

- manifests/profile/networking/firewall.pp
- spec/classes/profile/networking/firewall_spec.rb
- spec/classes/role/minimum_spec.rb
Dropping everything on IPv6 was causing problems for connections to
localhost by name. By mirroring our IPv4 rules, we get the same effect,
except that loopback connections are accepted.
> AEIM-2465 - Add explicit rules for IPv6

- files/pam.d/sshd-stretch
- manifests/role/chipmunk.pp
- spec/classes/role/chipmunk_spec.rb
This brings in a stock stretch /etc/pam.d/sshd config and introduces an
inline template to include that and then add the umask settings.
Specifically, the umask is set to 0002 on ssh logins, so rsync uploads
can preserve setgid and group write permissions readily with:
rsync -rzvtP --no-group --no-perms --chmod=ugo=rwX
This formula is mentioned in the rsync man page, in the --perms section.
> PFDR-263 - Add PAM/sshd config

- manifests/profile/www_lib/apache.pp
- manifests/profile/www_lib/vhosts/redirects.pp
- spec/classes/role/www_lib_vm_spec.rb
Support is needed for both http and https. I used redirect_vhost_http to redirect http to https and added an https vhost to handle the redirection of all source URLs to the single target under www.lib. Alternatives are welcome.
> AEIM-2467 Add redirect vhosts for copyright.umich.edu

- manifests/profile/hathitrust/apache/catalog.pp
- manifests/profile/hathitrust/apache/redirection.pp
redirect m.hathitrust.org to www.hathitrust.org (for root) or catalog.hathitrust.org (for everything else)
> HT-1845: redirects for m.hathitrust.org

- manifests/profile/apt/buster.pp
- manifests/profile/hathitrust/dependencies.pp
- spec/classes/role/ht_ingest_spec.rb
initial installation of jhove/libactivation-java doesn't work on stretch
currently because buster is stable (not testing) now
> HT-379: testing isn't buster any more

- templates/profile/hathitrust/ingest_service/feedd.service.erb
The default /tmp is 4G on the ingest machines, which was too small to
process some large images with imagemagick. This uses /ram, which a
corresponding change in lensoftruth has enlarged to 16G.
> HTS-135762 - use /ram as the tmpdir for HT ingest service

- manifests/profile/apt/buster.pp
Wasn't working with release; verified this should work with the actual apt pin file and the generated template here https://github.com/puppetlabs/puppetlabs-apt/blob/master/templates/pin.pref.epp
> change release to codename

- manifests/profile/docker.pp
- manifests/profile/kubernetes.pp
- spec/classes/profile/docker_spec.rb
- spec/classes/profile/kubernetes_spec.rb
This way, we'll be able to safely run apt-get dist-upgrade.
> AEIM-2384 - Pin docker and kubernetes to a version

- manifests/role/deploy_host.pp
- manifests/role/umich.pp
We have to pass the `internal_routing` parameter along through umich to
get to minimum, but otherwise, this is straightforward. The parameter is
used to preserve the docker-specific routes added when the engine
package is installed -- otherwise our firewall profiles clobber any
rules that are unrecognized.
> AEIM-2495 - Add docker profile to deployhost

- templates/unison/client/service.erb
- templates/unison/server/service.erb
Use an After directive to ensure unison clients and servers start after their data mount dependencies. The Require directive only ensures the mount is present but does not ensure ordering. It is acceptable for systemd units to have multiple After directives, similar to Require.
> AEIM-2429 Introduce an ordering dependency for unison on mounts.

- manifests/profile/prometheus.pp
- spec/classes/profile/prometheus_spec.rb
- templates/profile/prometheus/config.yml.erb
Since we don't manage our windows machines with puppet, this just uses a
static node list for each scraper to know what to scrape.
> AEIM-2248 - Scrape WMI exporters as well as node exporters

- manifests/profile/hathitrust/perl.pp
For EPUB identifiers, among other potential uses
> HT-1997: Add Noid.pm for arkid generation

- manifests/profile/clearinghouse/apache.pp
- manifests/profile/php73.pp
- manifests/role/clearinghouse.pp
- spec/classes/role/clearinghouse_spec.rb
- spec/default_facts.yml
- spec/fixtures/hiera/clearinghouse.yaml
- spec/fixtures/hiera/clearinghouse_config.yaml
This is mostly Aaron's work from the summer to add a puppet-managed apache config for clearinghouse, plus some updates to finalize the apache and php config. We will add puppet-manage mysql when that work is completed. Conor and the stakeholder want to move to the new AWS hosting now though.
The only change with a broader impact is an increase in our default PHP upload_max_filesize from 32M to 64M. It seemed simplest to increase the default rather than duplicate our full PHP 7.3 config for clearinghouse.
> AEIM-2008 add clearinghouse role

- manifests/profile/www_lib/apache.pp
- manifests/profile/www_lib/vhosts/apps_lib.pp
- spec/classes/role/www_lib_vm_spec.rb
Copying rather than abstracting seems like the right way to go here --
@skorner reports "In about 5 months we won't serve www.lib from our web
servers anymore and even before then the apps.lib vhost config will
likely start to diverge from what we have locally for www.lib."
> AE-7176: Copy www.lib vhost to apps.lib

- .fixtures.yml
- manifests/cert.pp
- manifests/profile/https_to_port.pp
- manifests/profile/letsencrypt.pp
- manifests/profile/prometheus.pp
- metadata.json
- spec/classes/profile/https_to_port_spec.rb
- spec/classes/profile/prometheus_spec.rb
- spec/default_facts.yml
- spec/defines/cert_spec.rb
- templates/profile/prometheus/rules.yml.erb
Adding an apache vhost to point 443 at localhost:9090, which requires keys. Adding letsencrypt keys, which require an apache vhost on port 80 for passing the letsencrypt challenge. Trying to use the simplest settings possible.
> AEIM-2568 - Add https reverse proxy to Prometheus

- manifests/profile/networking/sshd.pp
- manifests/role/chipmunk.pp
- templates/profile/networking/sshd_config.erb
We do a bit of fancy key and chroot management for Dark Blue, and
sshd_config does not yet support a drop-in directory or include pattern,
so we have to make an extension point. This is a regrettable workaround.
See also: https://bugzilla.mindrot.org/show_bug.cgi?id=2351
> PFDR-274 - Support sshd_config addons for Dark Blue

- files/pam.d/sshd-defaults
- manifests/profile/duo.pp
- manifests/profile/networking/sshd.pp
- manifests/profile/networking/sshd_group_umask.pp
- manifests/role/chipmunk.pp
- spec/classes/profile/duo_spec.rb
- spec/classes/profile/networking/sshd_group_mask_spec.rb
- spec/classes/profile/networking/sshd_spec.rb
- spec/classes/role/chipmunk_spec.rb
The way the Duo PAM module and the umask settings for Dark Blue were
being managed, they were clobbering each other. This is because the
chipmunk role was overwriting the file, and then the file_line for
pam_duo was modifying it each time.
This commit cleans up how /etc/pam.d/sshd is managed so it is a
concat_file that includes the stock config and then concat_fragments can
add to that the minimal custom file.
> PFDR-274 - Clean up pam/sshd config to avoid repeated corrections

- manifests/profile/hathitrust/apache/babel.pp
- spec/fixtures/hiera/hathitrust.yaml
I realized at the last minute that /useradmin in production is something else, so (at least until that can be retired) this will be at /usermanage. I don't want to change the name of the instance, and I would expect eventually this can replace what's at /useradmin.
> HT-2113: proxy app for useradmin production

- manifests/profile/hathitrust/ingest_jobs.pp
- spec/classes/role/ht_ingest_primary_spec.rb
- spec/fixtures/hiera/hathitrust.yaml
Tim reports (regarding the file this job processes): "It's definitely
obsolete. We have a umich process that manages the workflow for
locally-digitized volumes (that were "rejected" for scanning by google).
The "allrejects.txt" file was from an earlier iteration of the process,
which was rewritten about 5 years ago. So, Aaron should just remove
references to it. And since it's not a HathiTrust workflow, you
shouldn't have to mess with it either." -
https://github.com/hathitrust/post_zephir_processing/pull/1#issuecomment-573829040
I am wondering though if just removing all references to this job (and then manually purging the cron job on the server it runs on) is a preferred approach, or if we should instead do
```puppet
'get brittle books data':
ensure => 'absent';
```
and keep it …
> HT-2231: remove get_brittle_books_data

- templates/profile/prometheus/rules.yml.erb
This because we still have several machines that take longer than 10
minutes to boot. Also, if we want to know sooner than 30 minutes after a
problem happens, we should monitor that particular problem, rather than
the general problem of "a computer is off."
> Wait 30 minutes instead of 10 to alert if machines are off

- manifests/profile/base/hp.pp
- spec/classes/profile/base_spec.rb
Added the blacklist for the acpi_power_meter kernel module that generates the ACPI errors due to a firmware bug (fixable but not something we use so no need). The errors fill logs and clutter console displays.
Also fixed the typo of hpwdt (it was kpwdt).
> Blacklist acpi_power_meter, fix hpwdt name typo

- manifests/profile/prometheus.pp
- spec/classes/profile/prometheus_spec.rb
- templates/profile/prometheus/rules.yml.erb
This adds two rules to the general scraper profile, and the storage
device/mount is within hiera.
> AEIM-2667 - Add Dark Blue storage monitoring

- manifests/profile/hathitrust/ingest_service.pp
In rare cases ingest can get stopped in such a way that material ends up
in the repository even if it is incomplete. In the worst case, a zip
file can be put into place and appear intact, but in fact be incomplete
(see HT-1666)
> Disable ingest restart jobs

- manifests/profile/hathitrust/cron/mdp_misc.pp
Just adding a cron job for managing exclusivity. Runs at the same time (offset via config per datacenter) as the sessions cleaning; these are using different tables so shouldn't impact each other. Running simultaneously at both data centers would likely cause deadlocks/replication issues, though.
> add manage exclusivity cronjob for HT ETAS

- spec/defines/virtual_machine_spec.rb
- templates/virtual_machine/stretch.cfg.erb
This change is not the best:
```diff
-@domain
+(@title.split('.') + @domain.split('.')).drop(1).join('.')
```
If it were normal ruby code, I'd want to extract a method as a first
step to clarifying what's going on with this. But this is a template
file, so extracting a method bears an additional cost.
There are tests that represent this behavior, so I'm letting it stand as
is.
> AEIM-2593 - Include all but hostname in a VM's domain

- templates/profile/prometheus/rules.yml.erb
30 days is not long enough, so we'll wait 40 days instead.
> Wait longer for Windows to update

- data/common.yaml
We started doing a `unique` merge instead of a `first` merge, and that
pulls in versions specified in modules as well as those just in hiera.
> Remove extra ruby versions

- manifests/profile/ruby.pp
- spec/classes/profile/ruby_spec.rb
Ruby gems isn't working for jruby 1.7, so we want to purge it entirely.
While we work on that, this ensures there are no failing puppet
resources related to it in the meantime. We could silence the alert, but
then we might miss it if something else starts failing.
These changes should be reverted when 1.7 is gone, as is covered by
AEIM-2776.
> Don't manage jruby 1.7

- manifests/profile/ruby.pp
- spec/classes/profile/ruby_spec.rb
- spec/default_facts.yml
This will check every already-installed version of ruby and compare it
against the list of supported versions. If a version of ruby is
installed but not supported, it will be uninstalled.
> AEIM-2768 - Uninstall unwanted ruby versions

- manifests/profile/www_lib/vhosts/redirects.pp
I believe removing the config from redirects.pp is all that is needed to suffice AEIM-2785.
> Removed support.fulcrumscholar.org config from redirects.pp

- manifests/profile/ruby.pp
- spec/classes/profile/ruby_spec.rb
This lets us put off uninstalling 9.0.X on buzz and grog.
> AEIM-2776 - Stop managing jruby-9.0.X as well as 1.7.X

- manifests/profile/legacy/kubernetes.pp
- manifests/profile/legacy/kubernetes/haproxy.pp
- manifests/profile/legacy/kubernetes/stacked_controller.pp
- manifests/profile/legacy/kubernetes/worker.pp
- manifests/role/legacy/kubernetes/controller.pp
- manifests/role/legacy/kubernetes/gateway.pp
- manifests/role/legacy/kubernetes/worker.pp
- spec/classes/all_roles_spec.rb
- spec/classes/profile/legacy/kubernetes/haproxy_spec.rb
- spec/classes/profile/legacy/kubernetes/stacked_controller_spec.rb
- spec/classes/profile/legacy/kubernetes/worker_spec.rb
- spec/classes/profile/legacy/kubernetes_spec.rb
- spec/classes/role/kubernetes_spec.rb
- spec/fixtures/hiera/kubernetes.yaml
This is to make room for its radically different production replacement,
since we want the prototype to continue running until we're ready to
replace it.
This requires a s/kubernetes/legacy::kubernetes/g in the hieradata that
definitely needs to be tested on hatcher-k8s-* before this is safe to
merge.
> AEIM-2815 - Rename kubernetes legacy::kubernetes

- manifests/profile/www_lib/vhosts/staff_lib.pp
Minimal change. This works. Just needs a blessing.
> Add non-standard name for staff.lib cosign service to make it work

- lib/puppet/functions/is_publicly_accessible.rb
- manifests/profile/networking/firewall/ssh.pp
- spec/classes/profile/networking/firewall/ssh_spec.rb
- spec/fixtures/hiera/default.yaml
- spec/functions/is_publicly_accessible_spec.rb
Opening to all_trusted_machines is silly when most machines aren't even
on the right private VLAN. So instead we'll open ssh just to a select
few private bastion hosts.
> Open SSH differently on publicly inaccessible nodes

- spec/defines/virtual_machine_spec.rb
- templates/virtual_machine/stretch.cfg.erb
Only append our usual domain name when the VM hasn't specified one of its own.
> AEIM-2864 - Allow VM names to be FQDNs

- manifests/profile/www_lib/vhosts/www_lib.pp
- Remove the access control for `/cgi/l/login`, which was breaking
- Move the LocationMatch for SALI to the right section, public ON
> AEIM-2779 - Fix up directory/location directives

- manifests/apache/www_lib_vhost.pp
When setting up a virtual host for Cosign, using Require
(mod_authz_core) demands that we use:
```
<VirtualHost ...>
CosignProtected On
...
ShibCompatValidUser On
<Location /somewhere/login>
CosignAllowPublicAccess Off
AuthType Cosign
Require valid-user
</Location>
</VirtualHost>
```
> AEIM-2915 - Disable Shibboleth for Cosign virtual hosts

- manifests/role/app_host/prod_private.pp
When just including www_lib::mounts unqualified, the app hosts kept
trying to mount NFS and CIFS filesystems that were www-lib specific and
that they did not have access to. This was causing puppet to raise
errors due to the failed mounts.
This commit explicitly sets those lists of extra mounts to empty hashes
so that hieradata will be ignored.
> Mount only /www and /www-dev on private app hosts

- manifests/profile/haproxy/prereqs.pp
- spec/classes/profile/haproxy_spec.rb
Systemd already checks the config when running reload, but puppet was
running restart instead of reload. This tells it to run reload instead.
Additionally, this adds an exec that checks the config on every sync, so
that, if puppet applies an invalid config, not only will haproxy fail to
reload, but also puppet will repeatedly have this exec as a failing
resource.
> AEIM-2976 - Check haproxy config on every sync and when reloading

- manifests/profile/www_lib/cron.pp
On the old webservers, the press site was run directly by apache, so we
restarted it with pkill. On the newer VMs however, it's run by systemd,
so we need to restart it with systemd.
> AEIM-2978 - Restart press with systemd

- manifests/apache/www_lib_vhost.pp
- manifests/profile/www_lib/vhosts/staff_lib.pp
They were showing up as
AllowOverride None
Require all granted
<FilesMatch ".+(\.php)$">
SetHandler application/x-httpd-php
</FilesMatch>
CosignAllowPublicAccess off
But what we want is
AllowOverride None
-Require all granted
<FilesMatch ".+(\.php)$">
SetHandler application/x-httpd-php
</FilesMatch>
CosignAllowPublicAccess off
+AuthType Cosign
+Require valid-user
This does this while also adding a cosign_public_access_off_php5_dirs
parameter to the www_lib_vhost type, in the same style as
cosign_public_access_off_dirs, but adding the SetHandler for PHP5 as
well.
> AEIM-2980 - Fix PHP5 cosign-only directories

- manifests/profile/kubernetes/filesystems.pp
- spec/classes/role/kubernetes_spec.rb
This is required for ceph to recognize its storage volumes.
> AEIM-2989 - Install LVM on kubernetes worker nodes

- manifests/profile/kubernetes/keepalived.pp
- manifests/profile/kubernetes/router.pp
- spec/classes/profile/kubernetes/keepalived_spec.rb
- spec/classes/profile/kubernetes/router_spec.rb
- spec/fixtures/hiera/kubernetes/default.yaml
- templates/profile/kubernetes/keepalived/keepalived_01.erb
Currently, the NAT router changes the source IP address on all external requests to the cluster's public IP address. This ensures that the cluster will claim a private IP address when communicating on a specified CIDR.
> AEIM-3009 - Kubernetes can communicate on an external private VLAN

- manifests/profile/hathitrust/ingest_jobs.pp
The jobs that fetched new data from zephir run at 3:05 AM, so these (which ran at 3 AM) were potentially using data that was a day behind what was fetched from zephir.
> Adjust timing of ingest daily jobs

- manifests/role/kubernetes/backup_gateway.pp
- manifests/role/kubernetes/controller.pp
- manifests/role/kubernetes/etcd.pp
- manifests/role/kubernetes/primary_gateway.pp
- manifests/role/kubernetes/worker.pp
- spec/classes/role/kubernetes_spec.rb
Apparently rook/ceph gets upset when clocks disagree with one another,
and kubernetes nodes should always be running NTP. This tells all our
kubernetes nodes to pull in our NTP profile.
> AEIM-3023 - Install NTP to fix clock skew

- manifests/profile/kubernetes/destination_port/gelf_tcp.pp
- manifests/profile/kubernetes/haproxy.pp
- manifests/role/kubernetes/worker.pp
- spec/classes/profile/kubernetes/destination_port_spec.rb
- spec/classes/profile/kubernetes/haproxy_spec.rb
- templates/profile/kubernetes/haproxy/services.d/gelf_tcp.cfg.erb
This is straightforward; it adds an HAProxy pair for GELF similar to how
we support https_alt.
> AEIM-3022 Expose Graylog via GELF/TCP to datacenter nodes

- manifests/profile/hathitrust/imgsrv.pp
For as long as we retain email notifications for this cron job, we should only need to know if it generates an error. Haproxy monitoring covers the service-related alerts.
> Silence imgsrv watchdog stdout. Retain notification for stderr

- manifests/profile/hathitrust/perl.pp
This reverts commit fc4efb9ef7bfdd2ba3e5e3a8770512d3b1c9c53c, reversing
changes made to c1059a14b61689cbb02d4b7925f7b0d07ef3a2a7.
The CPAN version pulled in too many depencies, and (because of the
implementation of nebula::cpan) did not automatically update. To get the
update to happen this way we would have to uninstall the Debian version
and then wait for the CPAN version to build, leaving production broken
in the meantime.
A newer version of Image::Info is packaged by buster, so I suggest
installing that version in our local deb repo and then just updating
production. We have verified that new version works in development and
on ht-web-testing.
> AE-8443: Revert #380 (cpan version of image::info)

- manifests/haproxy/service.pp
- spec/defines/haproxy_service_spec.rb
- templates/profile/haproxy/throttling.erb
We've been serving 509s when throttling connections, but 5xx errors
imply something wrong with the server. The correct HTTP status code is
429, which correctly implies disallowed behavior on part of the client.
> AEIM-3108 - Throttle with 429 instead of 509

- manifests/haproxy/service.pp
- manifests/profile/haproxy.pp
- manifests/profile/hathitrust/apache.pp
- spec/classes/profile/haproxy_spec.rb
- spec/classes/profile/hathitrust/apache_spec.rb
- spec/defines/haproxy_service_spec.rb
Uses "set-weights.rb" from ae-utils to set weights dynamically based on
server load
Tested on ictc-haproxy-001 with ictc-ht-web-*
> Dynamic weighting for haproxy back ends

- manifests/profile/prometheus.pp
- templates/profile/prometheus/config.yml.erb
- templates/profile/prometheus/exporter/haproxy/defaults.sh.erb
- templates/profile/prometheus/rules.yml.erb
Three new alerts:
1.  Notice when prometheus isn't collecting metrics
2.  Notice when a disk will fill up within 4 days (based on the past 24 hours)
3.  Notice when a disk will fill up within 4 hours (based on the past hour)
Also tweaked the DeepBlueDataProdStoragePressure alert to give it a
threshold of 3T instead of 2T, since it takes less than 24 hours to go
from 2T free to 0B free.
Also added the hostname to the prometheus config so that the
PrometheusNotRunning alert will produce a helpful error message (without
this, all we'd be able to get is "one of the prometheus servers isn't
working" without any indication as to which).
> AEIM-3213 - Add some new alerts for filling up disks

- templates/profile/prometheus/rules.yml.erb
We no longer have any red hat 5 machines, so we don't need these alerts
anymore.
> AEIM-3215 - Remove RHEL5 alerts

- manifests/profile/prometheus.pp
- manifests/profile/prometheus/exporter/node.pp
- manifests/profile/puppet/query.pp
- spec/classes/profile/prometheus/exporter/node_spec.rb
- spec/classes/profile/prometheus_spec.rb
- templates/profile/prometheus/config.yml.erb
- templates/profile/prometheus/exporter/node/pushgateway.sh.erb
The pushgateway is two things:
1.  To a cronjob, it's a place to push metrics from the most recent run.
2.  To a scraper, it's an exporter like any other.
In other words, the pushgateway maintains no history -- that's the
scraper's job.
This commit also opens the port on the scrapers that the pushgateway
uses to all nodes it is currently scraping.
There are 2 things to consider:
1.  By default, the pushgateway's data does not persist (this is default
even when not run in a container). I did not change this default. So
whenever the pushgateway restarts, the scraper will start seeing
null for all cronjob metrics until next time the job runs.
2.  Pushing metrics to the pushgateway is a one-line curl, but we ought
to have puppet distribute that one line in /usr/local/bin on all
nodes. That …
> AEIM-2642 - Add pushgateways to prometheus node scrapers

- templates/profile/hathitrust/ingest_service/feedd.service.erb
@daaang  reported that ingest did not automatically get re-enabled on reboot because of the missing WantedBy.
> Make feedd.service enableable

- templates/profile/prometheus/rules.yml.erb
At least one of the clients can be execced to take at least 90 minutes
to run to completion, so a 30 minute window is entirely inappropriate.
> Increase unison alert window from 30m to 2h

- templates/profile/prometheus/rules.yml.erb
We expect this disk to appear to fill up constantly, and it's supposed
to clear itself out. If it's full, that could be fine. If it's full for
any length of time, something is probably wrong.
> Remove /htdataden from generic disk alerts; add specific alert

- manifests/profile/hathitrust/clamav.pp
- manifests/role/hathitrust/ingest_indexing.pp
- spec/classes/role/ht_ingest_spec.rb
There are some cases where we want HT ingest to virus scan material prior to ingest. This adds clamav and enables the clamav-daemon for use by https://github.com/hathitrust/feed/blob/master/lib/HTFeed/PackageType/EMMA/VirusScan.pm
> HT-2749: install clamav-daemon on ingest machines

- manifests/profile/www_lib/vhosts/fulcrum.pp
This implementation is similar to that in profile/hathitrust/apache (and .../babel):
https://github.com/mlibrary/nebula/blob/master/manifests/profile/hathitrust/apache.pp#L39-L45
https://github.com/mlibrary/nebula/blob/master/manifests/profile/hathitrust/apache/babel.pp#L38-L41
> AE-9010 - Restrict Fulcrum metrics to datacenter networks

- templates/profile/prometheus/rules.yml.erb
This is our second unison implementation that we expect to take a very
long time, so we should probably find something other than unison to
solve these multi-datacenter problems. Until then, the bandaid is that
we won't receive alerts.
> Stop alerting when htapps-cache unison takes too long

- templates/profile/prometheus/rules.yml.erb
This is a straightforward addition. The slack notifications in the alertmanager config already check for `{{ .CommonAnnotations.dashboard }}` and conditionally include a link.
I chose to link to the node page. We might be able to link to the specific report, but I don't know whether that info is included in the alert, and it's useful to see the node at a glance anyway.
cf. https://prometheus.io/docs/alerting/latest/notification_examples/
> Add puppetboard dashboard link to puppet alert annotations

- manifests/profile/www_lib/vhosts/deepblue.pp
The first attempt at this had a space between the rewrite flags. This version expands the flag names and eliminates the space.
> AE-9671 - Redirect root of deepblue.lib to www.lib (fixed)

- templates/profile/prometheus/rules.yml.erb
S3 mounts don't have inodes, so the alert is meaningless.
> Stop monitoring inode usage on s3fs filesystems

- manifests/profile/prometheus/exporter/node.pp
While these hosts were scraped by a prometheus server in our own
datacenter, we needed to refer to them by their public ip address. Now
that we are running prometheus servers in AWS, they can communicate over
their own LAN.
> Use private IP addresses for EC2 node metrics

- manifests/profile/logrotate.pp
- spec/classes/profile/logrotate_spec.rb
Sometimes wtmp fills up disks on our more thinly-provisioned servers. By
setting this to weekly instead of monthly, we expect that the log files
will take up less disk space.
> Rotate wtmp and btmp logs weekly instead of monthly

- manifests/profile/hathitrust/apache/babel.pp
- spec/fixtures/hiera/hathitrust.yaml
This adds the Apache configuration to:
- reverse proxy to Dex from Apache, providing relevant Shibboleth headers
- automatically force authentication with Shibboleth at the correct time when authenticating through Dex
- Consume an entityID IdP hint parameter and redirect the user to log in through Shibboleth
There are certainly some duplications here with otis; if we were committed to puppet-apache + proxied access to apps in the long term I would want to consider refactoring this à la what we did for moku apps, but my sense is that we aren't committed to puppet-apache in the long term, that we will hopefully not need to use the apache basic auth for proxied apps all that much longer, and that eventually (at least for HathiTrust) I'll likely eventually want to containerize Apache itself, …
> HT-2959: Shibboleth + Dex OIDC <-> SAML proxy

- manifests/profile/kubernetes/dns_server.pp
- spec/classes/profile/kubernetes/dns_server_spec.rb
- spec/fixtures/hiera/kubernetes/default.yaml
This is to support Isilon SmartConnect, which relies on delegating
queries for a particular zone to its private DNS server.
> Support for private DNS zone in dnsmasq for k8s cluster

- manifests/profile/hathitrust/rsync.pp
- manifests/profile/hathitrust/secure_rsync.pp
- manifests/role/hathitrust/datasets.pp
- spec/classes/role/ht_datasets_spec.rb
- spec/fixtures/hiera/hathitrust.yaml
- templates/profile/hathitrust/rsync/rsyncd.conf.erb
- templates/profile/hathitrust/secure_rsync/secure-rsync.service.erb
- templates/profile/hathitrust/secure_rsync/stunnel.conf.erb
This migrates the unencrypted rsync and the stunnel+rsync functionality that was on quik-1. Paths and IP addresses are configured in the corresponding branch in lensoftruth.
> HT-3017: rsyncd for datasets

- templates/profile/prometheus/rules.yml.erb
Our first attempt at a ram alert was to send a page if a host ever has
less than 250M of available memory. In practice, this was noisier than
we'd hoped, since running out of available memory isn't necessarily
indicative of a problem.
We're replacing the rule with two new rules:
1.  HostOomKillDetected will send a page but then quickly resolve itself
whenever a host OOM-kills something.
2.  HostUnderMemoryPressure will send an info alert whenever there are
more than 1,000 major page faults (grep pgmajfault /proc/vmstat) per
minute. Rather than picking a number of bytes that should be free,
this detects poor performance likely due to low memory.
> Alert on OOM-kill instead of on < 250M free memory

- manifests/profile/tools_lib/apache.pp
On some of the bigger projects, it's taking longer than 60 seconds for
jira to load pages, so mod_proxy is timing out, since it's currently
defaulting to the value of Timeout, which the puppet apache module sets
to 60 seconds by default.
Left to its own, apache has a default timeout of 300s, so we're not
really doing anything all that weird by having a 5 minute proxy timeout.
> AE-10100 - Increase jira ProxyTimeout from 60s to 300s

- manifests/profile/hathitrust/secure_rsync.pp
Allow us to exclude them from certificate checks when staging them to
puppet-master
> Move secure rsync certs to self-signed dir

- manifests/profile/hathitrust/cron/catalog.pp
- manifests/profile/hathitrust/cron/mdp_misc.pp
This stems from an error made when originally migrating these jobs, and perhaps before that; the getall.sh cron job should in fact run at both sites.
The catalog cron job profile is only included in the HT global primary
role; the mdp_misc one is included in the site primary.
I wonder if perhaps we should rename mdp_misc to "once per site" and
catalog to "once anywhere", or if that isn't really worth it.
> HT-3073: Run catalog cron job getall.sh at both sites

- manifests/profile/hathitrust/apache/babel.pp
- spec/fixtures/hiera/hathitrust.yaml
This seems to be the easiest way to inject a different host for ptsearch
solr at different data centers. Right now deployment assumes
configuration will be the same at both data centers and differences will
be handled by `/etc/hosts`. However, deploying ptsearch solr in Kubernetes at
multiple data centers with proxied ingress via HTTPS means we need
separate hostnames so that letsencrypt can successfully generate a
cert. We considered several options including disabling cert
verification, alternative ingress setups, etc, and this seems this least
disruptive; it also gives us an easy path to vary the solr for
test/preview in addition to production.
> HT-3042: add PTSEARCH_SOLR env var

- templates/profile/prometheus/rules.yml.erb
We check Fedora every minute. If it does not respond for 15 minutes, we
send a page level alert to investigate promptly.
> SYS-239 - Alert when Fedora is down for Deep Blue Data

- manifests/profile/hathitrust/apache/babel.pp
- spec/fixtures/hiera/hathitrust.yaml
Getting it via config required committing to slip-lib repo, which we did
not want to do. This brings the config for ptsearch (somewhat) more in line with what we are doing with the other kubernetes services with basic auth.
> HT-3042: add basic auth for ptsearch solr to env

- spec/classes/profile/monitor_pl_spec.rb
It's not clear what conditions aggravate this, but I was seeing
different output on the exact same version of Ruby on my workstation and
in a container. This is presumably the built-in psych implementation
varying in some way that would be hard to track down.
The regexes achieve the same matching, but are not sensitive to the
whitespace difference.
> Use regexes to match YAML output for concat_fragments

- manifests/profile/hathitrust/cron/mdp_misc.pp
- spec/classes/profile/hathitrust/cron/mdp_misc_spec.rb
First time dealing with puppet, so I really need someone to check my work.
All in mdp_misc.pp
* Set an $sdr_environemnt variable without MAILTO, and
use it to define a default env ($sdr_environment +
MAILTO=${mail_recipient}`) that can be overridden for items that
take care of their own mail
* Change "harvest proxy downloads", "data api log monitor", and
"manage mbook sessions" to both:
* use the new, mailto-free environment
* only send email on error (e.g., use || instead of |)
> Reduce cron email notifications

- manifests/profile/hathitrust/hosts.pp
- spec/classes/profile/hathitrust/hosts_spec.rb
- spec/fixtures/hiera/hathitrust.yaml
ptsearch is now in kubernetes; endpoint is configured
via environment variable, not /etc/hosts
> Remove references to ptsearch host

- manifests/profile/hathitrust/apache/redirection.pp
This just copies the port 80 config for http://hathitrust.org to https://hathitrust.org.
> Was missing redirect for https://hathitrust.org

- manifests/profile/fulcrum/logrotate.pp
- manifests/role/fulcrum.pp
- spec/classes/profile/fulcrum/logrotate_spec.rb
These settings are copied right from bulleit-1 for heliotrope-production
logging.
> Add log rotation to fulcrum.

- manifests/profile/hathitrust/apache/babel.pp
- manifests/profile/www_lib/vhosts/fulcrum.pp
By default, Apache will go ahead and set the header to the literal value
"(null)" rather than an empty string, which results in unexpected
behavior when downstream applications process "(null)" as if it's a real
value.
> Only set Shib headers when env is present

- manifests/profile/hathitrust/apache/babel.pp
- manifests/profile/www_lib/vhosts/fulcrum.pp
When we always set the X-Shib header (regardless of whether the env var
from mod_shib was present), any client-supplied header would get wiped
out. When conditionally setting the header, a client-supplied header
could be injected if mod_shib does not supply a value. This is not the
behavior we want.
I've tested this on beta-1.babel.hathitrust.org and verified that 1) this pattern (`RequestHeader unset` followed by a conditional `RequestHeader set`) still passes through the Shib-supplied env vars and that 2) with this pattern, client-supplied headers don't make it through.
> Unset Shib headers before setting to prevent spoofing

- manifests/profile/vmhost/host.pp
- manifests/virtual_machine.pp
- spec/classes/profile/vmhost/host_spec.rb
- spec/defines/virtual_machine_spec.rb
The new vmhosts use Ubuntu, which uses netplan for network configuration
instead of /etc/network/interfaces. This allows us to use more
meaningful interface names instead of br0 and br1; however, that means
we need to be able to configure the bridge names per vmhost.
> HT-3278: allow overriding bridge interface names in vm

- manifests/profile/shibboleth.pp
- manifests/role/webhost/htvm.pp
This should, in theory, validate proposed changes to shibboleth2.xml before putting them in place. I thought that shibd would refuse to reload an invalid shibboleth2.xml (and that may be true), but it also (surprisingly to me) causes apache / mod_shib to fail. 
This does NOT validate changes to other Shibboleth configuration files (e.g. attribute-map.xml or attribute-policy.xml); I'm not sure how we would do that with either `shibd -t` or with the puppet configuration that just puts the entire directory in place, but I'm also reasonably certain that I've pushed out changes to those files with errors and that it does not bring down the web server, so... :shrug: 
The upcoming change to shibboleth SP version 3 in Debian 11 might give us a good chance to rethink workflow here. If nothing …
> Add validate_cmd for shibboleth2.xml

- templates/profile/prometheus/rules.yml.erb
This alert was flapping because sometimes the server was responding with
null values intermittantly. Using the avg_over_time() function over a
period of 10 minutes shouldn't change the way this alert works, but it
will tolerate the occasional lack of response without flapping.
> Fix flapping windows update alert

- manifests/profile/prometheus.pp
- spec/classes/profile/prometheus_spec.rb
- templates/profile/prometheus/rules.yml.erb
I added an argument to `docker run` that should have been an argument to
the running container. I noticed the problem because I happened to
check; the pushgateways have been down since that change, and we haven't
heard anything because we didn't have an alert for any exporters being
down other than the node exporters.
> Move command argument to the right place; add alert

- manifests/role/webhost/fulcrum_www_and_app.pp
HAProxy checks /monitor/monitor.pl for backend liveness, and that is set
up in apache::base. However, we did not have a default vhost for
requests via IP/fqdn, so the checks were failing. This adds the default
vhost to the fulcrum+apache role. Ideally, it would be in the profile,
but that would collide with the standard inclusion via misc on general
servers.
> HELIO-4186 - Add default vhost for monitoring

- manifests/role/webhost/fulcrum_www_and_app.pp
There are a few dependencies in monitor.pl, so we add the perl profile.
This is a bummer because the minimal server is getting progressively
bloated... but, the HAProxy http checks depend on /monitor/monitor.pl.
It's slightly preferable to keep that consistent for the time being than
to change the global HAProxy configs to allow a given service to have a
different check or to have something else running at that request path.
> HELIO-4186 - Add perl dependencies for monitor.pl

- manifests/profile/hathitrust/perl.pp
Per @respinos. This module is not available via Debian.
> DEV-7: perl module for new geoip format

- manifests/profile/hathitrust/php.pp
Required to eliminate use of Horde.
This commit should be applied to the bullseye branch as well.
> HathiTrust DEV-230: Add php-yaml

- .fixtures.yml
- manifests/profile/hathitrust/dependencies.pp
- manifests/profile/hathitrust/perl.pp
- manifests/profile/hathitrust/php.pp
- manifests/profile/shibboleth.pp
- manifests/role/webhost/htvm/test.pp
- metadata.json
- spec/classes/role/htvm_webhost_spec.rb
- templates/profile/dns/smartconnect/named.conf.options.erb
This should add most of what's needed for debian 11 support for HT without breaking anything for debian 9. This is mostly ported from https://github.com/mlibrary/nebula/tree/ht-debian-11 but keeping conditionals to support both stretch and bullseye. ~Still to-do is to add back some of the tests from the ht-debian-11 branch that are not yet replicated here.~ The tests are present now.
> Debian 11 support

- manifests/profile/fulcrum/logrotate.pp
- manifests/profile/logrotate.pp
- spec/classes/profile/fulcrum/logrotate_spec.rb
- spec/classes/profile/logrotate_spec.rb
This PR includes a commit that fixes fulcrum application log rotation and a commit that fixes our override of btmp and wtmp log rotation.
> 20220525 logrotate bugfix

- manifests/profile/hathitrust/apache/babel.pp
- spec/classes/profile/hathitrust/apache/babel_spec.rb
This supports the need to vary `CRMS_INSTANCE` based on whether a vhost is development or production (-ish).
- `CRMS_INSTANCE=production` for actual production as well as for `preview.babel.hathitrust.org`
- Not set by default elsewhere
This isn't the prettiest fix. Currently, I'm expecting to override this via hiera where needed -- while it might be nice to set it via the test vs. prod role, that would (I think) necessitate changes to a long chain of included files:
- `nebula::role::webhost::htvm::test` and `::htvm::prod` both include
- `nebula::role::webhost::htvm` includes
- `nebula::profile::hathitrust::apache` includes
- `nebula::profile::hathitrust::apache::babel`
If anybody has a more elegant way to vary this than what's given here, I'm all for it, but I don't think it's worth …
> HathiTrust DEV-316: CRMS_INSTANCE only set for production

- manifests/profile/hathitrust/apache.pp
- manifests/profile/hathitrust/apache/babel.pp
- manifests/profile/hathitrust/apache/catalog.pp
- manifests/profile/hathitrust/apache/crms_training.pp
- manifests/profile/hathitrust/apache/www.pp
- spec/classes/profile/hathitrust/apache/babel_spec.rb
- spec/classes/profile/hathitrust/apache_spec.rb
This is required for validating the "target" parameter in Shibboleth
sign on.
This also splits out crms-training to a separate vhost; this is required
so that Shibboleth knows the proper return target rather than having to
differentiate between crms-training.babel.hathitrust.org and
babel.hathitrust.org
> Set UseCanonicalName

- manifests/profile/hathitrust/apache/babel.pp
- manifests/profile/hathitrust/apache/crms_training.pp
We rarely rely on the SP to use the configured WAYF session initiator;
rather, the applications redirect to the WAYF as necessary. However,
there are cases when we do, especially with Dex. This change ensures
that we redirect to the WAYF for the vhost we're accessing rather than
always redirecting to https://babel.hathitrust.org
> HathiTrust DEV-345: fix redirect to WAYF in dev

- manifests/profile/http_fileserver.pp
- spec/classes/profile/http_fileserver_spec.rb
Where we previously used incommon for everything, we're starting to use
letsencrypt now, which has a different chain.
> Parameterize chain_crt for http fileservers

- manifests/profile/www_lib/vhosts/deepblue.pp
This should make it impossible for outside actors to place iframes around Deep Blue content. This could almost certainly be set by the application and/or in tomcat, but we saw no reason not to set it here.
> TDX #3266774 - Restrict iframes for Deep Blue Documents

- manifests/profile/known_host_public_keys.pp
- manifests/profile/kubernetes/dns_client.pp
- manifests/profile/kubernetes/dns_server.pp
- manifests/profile/kubernetes/keepalived.pp
- manifests/role/minimum.pp
- spec/classes/profile/known_host_public_keys_spec.rb
- spec/classes/profile/kubernetes/dns_client_spec.rb
- spec/classes/profile/kubernetes/dns_server_spec.rb
- spec/classes/profile/kubernetes/keepalived_spec.rb
- spec/fixtures/hiera/kubernetes/default.yaml
As of writing, this will only affect the known hosts files on kubernetes gateway servers, but it also sets the stage for us to make a bastion host with always up to date known hosts.
Since exported resources are always a bit unintuitive, I'll take a moment to go over the intentions for bastion hosts:
1.  I want to use a bastion host to be able to connect to any accessible host without managing my local known_hosts file. (This is made possible by the known_host_public_keys profile.)
2.  I want to use a bastion host to be able to connect to private kubernetes hosts, using whichever gateway is currently claiming the cluster ip address as a jump host, without needing to specify primary or backup by name. (This is made possible by the addition made to the keepalived kubernetes profile.)
3.  I …
> Export ssh public keys for /etc/ssh/ssh_known_hosts files

- manifests/profile/hathitrust/perl.pp
Once caveat: trying to install this module on dev-2.babel with the `cpan` command resulted in an error seemingly related to the `ex::monkeypatched` dependency (yeah, nothing at all sketchy there). But, I was trying to do a local install on a chunk of filesystem under my control, which is nontypical usage.
> Add MARC::File::MiJ Perl module for HathiTrust

- manifests/profile/kubernetes/bootstrap/etcd_config.pp
- spec/classes/profile/kubernetes/bootstrap/etcd_config_spec.rb
- spec/fixtures/hiera/kubernetes/default.yaml
- templates/profile/kubernetes/etcd/etcd.yaml.erb
Config is written to /tmp on etcd nodes, iff etcd_initial_cluster var is defined for the present cluster.
This approach requires moving /tmp/etcd.yaml manually. Could also write directly to /etc if we aren't concerned about etcd coming up w/o proper certs (or add additional conditional).
> Generate etcd yaml with erb

- manifests/profile/puppet/master.pp
- spec/classes/profile/puppet/master_spec.rb
This practice has always been (a) weird and (b) of questionable value. The idea was that we're talking about the directories that puppet distributes files from, and the question is where those files come from. If they're unmanaged, when someone has to copy them by hand when creating a new puppetserver.
With this code, it was possible to create a new puppetserver and let the old puppetserver hand it all these files. In practice however, it also means that most of the time, when there's exactly one puppetserver, every 30 minutes, the puppetserver checks to make sure that every single file matches... itself. It's an increasingly expensive operation that cannot possibly accomplish anything of value.
Now that we're starting to add some certificate renewal automation to our existing certificate …
> Stop managing fileserver directories on the puppetserver

- manifests/profile/kubernetes/dns_server.pp
- spec/classes/profile/kubernetes/dns_server_spec.rb
Without this configured, dnsmasq was checking every upstream for dns requests that were basically for `.cluster.default`. By setting this, dnsmasq will know that it is the authority for the domain, and it won't send a nonsense request upstream.
> Configure dnsmasq with the local domain

- manifests/profile/www_lib/apache/misc.pp
- manifests/profile/www_lib/vhosts/redirects.pp
- spec/classes/role/www_lib_vm_spec.rb
This domain has been sunset per the Library Copyright office and in coordination with ITS.
> Purge support for copyright.umich.edu

- .fixtures.yml
- metadata.json
- spec/classes/role/htvm_webhost_spec.rb
This is a minimal change to the `debian_11_support` branch to fully support PHP with Debian 11.
:warning: **DO NOT MERGE UNTIL ALL STRETCH MACHINES ARE RETIRED**
> Update php module to >= 8.0.0

- manifests/profile/fulcrum/app.pp
There is no good way to use something shell-compatible in systemd and there is no good way to use something systemd-compatible in the shell.
So, we JRO: Just Repeat Ourselves.
> Set Fulcrum env vars in .profile, not only in systemd EnvironmentFile

- manifests/profile/fulcrum/app.pp
- templates/profile/fulcrum/imagemagick-policy.xml.erb
The large images and PDFs that we process require a specialized configuration for ImageMagick.
> Add ImageMagick policy for fulcrum app servers

- manifests/profile/fulcrum/app.pp
- templates/profile/fulcrum/fulcrum-rails.service.erb
- templates/profile/fulcrum/fulcrum-resque.service.erb
- templates/profile/fulcrum/fulcrum.env.erb
We have thoroughly proven out jemalloc to mitigate the OOM issues for the app, and it requires no application changes, only environment. We're also adding automatic restarts to the systemd unit in case of other kinds of failure.
> Add jemalloc and auto-restarts for Fulcrum

- manifests/profile/fulcrum/app.pp
- templates/profile/fulcrum/fits.xml.erb
There are some content type settings honed over the years that we need to apply for FITS. This commit begins to manage the global config.
> Manage fits.xml for Fulcrum

- manifests/profile/fulcrum/logrotate.pp
The logs for keycard and checkpoint are currently going to the current release directory, inside db/. They are also currently quite noisy, so we make sure to rotate them. They will probably go to the shared directory and will be picked up by the normal rules at some point.
> Add logrotate for keycard/checkpoint

- manifests/profile/www_lib/vhosts/mgetit.pp
- manifests/profile/www_lib/vhosts/www_lib.pp
- spec/classes/role/www_lib_vm_spec.rb
There is no valid weblogin use case for www.lib, so we can remove it.
Also purge Cosign from mgetit.lib where it was never in use.
> Purge Cosign from the www.lib fallback vhost

- manifests/profile/www_lib/php.pp
- manifests/profile/www_lib/vhosts/apps_lib.pp
- manifests/profile/www_lib/vhosts/publishing.pp
- manifests/profile/www_lib/vhosts/staff_lib.pp
- manifests/role/webhost/www_lib_vm.pp
- templates/profile/apache/authz_umichlib.conf.erb
Specific details of the changes:
- PHP has moved the json module into the core as of 8.x
- Parameterization that exists in php.pp is nice, but not useful considering www_lib::php is only used in one role and the version is not parameterized in the three vhosts that use modern php/fpm or in the authz file handler entry
- Thus I just updated the default from 7.3 to 8.1
- Leave the legacy 5.6 install as-is for legacy script support.
- Also remove the vestigial comment in the role from when we used www_lib::php73 directly (circa 2020)
These changes were applied to macc-www-lib-testing and verified by Eliot.
> Switch PHP 7.3 to 8.1 for "www-lib" VMs

- manifests/profile/prometheus.pp
- manifests/profile/prometheus/exporter/node.pp
- spec/classes/profile/prometheus/exporter/node_spec.rb
- spec/classes/profile/prometheus_spec.rb
- templates/profile/prometheus/exporter/node/pushgateway.sh.erb
- templates/profile/prometheus/exporter/node/pushgateway_advanced.sh.erb
The other script only allowed for two specific metrics (last_success and duration_seconds). This one allows for setting whatever metrics you want, deleting them, and querying existing values. All the while, it attaches all the host-specific labels that cronjobs should not have to track.
You can also just ask the script for those host-specific details if you want to do your own curling and json parsing. I'm not trying to protect anyone from the pushgateway API here; I only want to make it easier.
> Add pushgateway_advanced script for flexible instrumentation

- templates/profile/www_lib/check_press.sh.erb
We don't currently know how often this script actually does restart the press service. With this change, the script will increment a counter on the pushgateway every time it actually runs systemctl restart press, and if we're ever interested, we'll be able to see how often it comes up, if ever.
> Modify press_fcgi_check to report total restarts

- manifests/apache/www_lib_vhost.pp
- manifests/profile/apache/auth_openidc.pp
- manifests/profile/www_lib/apache/misc.pp
- manifests/profile/www_lib/cron.pp
- manifests/profile/www_lib/dependencies.pp
- manifests/profile/www_lib/vhosts/apps_lib.pp
- manifests/profile/www_lib/vhosts/datamart.pp
- manifests/profile/www_lib/vhosts/deepblue.pp
- manifests/profile/www_lib/vhosts/fulcrum.pp
- manifests/profile/www_lib/vhosts/mgetit.pp
- manifests/profile/www_lib/vhosts/midaily.pp
- manifests/profile/www_lib/vhosts/openmich.pp
- manifests/profile/www_lib/vhosts/press.pp
- manifests/profile/www_lib/vhosts/search.pp
- manifests/profile/www_lib/vhosts/staff_lib.pp
- manifests/profile/www_lib/vhosts/www_lib.pp
- spec/classes/profile/www_lib/cron_spec.rb
- spec/classes/role/www_lib_vm_spec.rb
- spec/fixtures/hiera/www_lib.yaml
- templates/profile/apache/auth_openidc.conf.erb
- templates/profile/apache/authz_umichlib.conf.erb
- templates/profile/www_lib/check_press.sh.erb
The auth related changes are in two commits to reflect general mod_auth_openidc support in apache vs changes specific to www_lib.
The press_fcgi_check script commit is included as that change was needed while this branch was live in production.
> Add mod_auth_openidc support and migrate from cosign to auth_openidc for www_lib profile and vhosts

- manifests/profile/networking/firewall/ssh.pp
- spec/classes/profile/networking/firewall/ssh_spec.rb
Not sure why, but the `is_publicly_accessible()` function appears to be flapping, which occasionally causes inaccessibility due to machines incorrectly reporting to be private-only machines.
This way, all machines will always trust ssh coming from trusted CIDRs. It should have no impact on private hosts, since they're already behind a NAT router that should make them unroutable.
And if public-ip-address hosts occasionally flap and get a few 10-net ssh allowances? No harm done, really.
> Always trust umich::networks::all_trusted_machines for SSH

- manifests/profile/hathitrust/apache.pp
- manifests/profile/hathitrust/apache/old_www.pp
Add vhost for old.www.hathitrust.org - serves a static archive of the old Drupal site. Done analagously to crms-training.babel.hathitrust.org. This static archive should not have any php or .htaccess overrides - just index.html.
> HathiTrust DEV-792: old.www.hathitrust.org

- manifests/role/webhost/htvm/test.pp
- spec/classes/role/htvm_test_webhost_spec.rb
We need node/npm installed to support building the production css/js components, but do not currently need/want it in production.
nebula::role::webhost::htvm::test is the role used by the dev/test/preview HT web VMs.
> DEV-864 - install current lts node for ht dev hosts

- manifests/profile/hathitrust/apache/redirection.pp
- manifests/profile/hathitrust/cron/mdp_misc.pp
- spec/classes/profile/hathitrust/cron/mdp_misc_spec.rb
* Runs wordpress cron once an hour
* Hits production vhost via localhost (htaccess restricts access to wp_cron.php from elsewhere)
* redirect from http://old.www.hathitrust.org -> https://old.www.hathitrust.org
> HT DEV-849 - run wordpress cron from cron

- manifests/profile/hathitrust/cron/statistics.pp
- The hourly job ran cron jobs inside Drupal; we aren't running Drupal any more so we don't need that.
- The "RSS file" stuff appears to have driven a block on the Drupal web site, which we aren't using any more
- The publish on demand output hasn't changed in over 6 years, and is no longer a maintained service.
The remaining "stats" jobs generate textual output that is still useful for the time being.
> TTO-96 - remove unnecessary drupal cron jobs

- manifests/profile/hathitrust/apache/babel.pp
There is one particular IP address that has been issuing a large number of requests like
```
OPTIONS /cgi/pt/error
```
For whatever reason this wasn't being caught by the `DirectoryMatch` directives. This change should ensure that it does. I will verify on preview.babel that this doesn't interfere with any Shibboleth stuff.
> Prevent badrobots etc at location /

- .github/dependabot.yml
- .github/workflows/ci.yml
- Gemfile
- docker-compose.test.yml
- actions/checkout v2 => v3
- dependabot for gh workflows
- added parallel_tests gem, make `bundle exec rake parallel_spec` the default for ci
> update actions/checkout, add dependabot

- manifests/profile/www_lib/vhosts/search.pp
There were some odd conflicts for Search, where people were being taken through reauthentication. It has something to do with multiple data centers and server-side sessions/caches. The app can now manage OIDC logins, so we are bypassing the module here.
> Allow Search to manage its own auth via OIDC

- spec/classes/all_roles_1_spec.rb
- spec/classes/all_roles_2_spec.rb
- spec/classes/all_roles_3_spec.rb
- spec/classes/all_roles_4_spec.rb
- spec/classes/all_roles_5_spec.rb
- spec/classes/all_roles_spec.rb
- spec/classes/profile/hathitrust/dependencies_spec.rb
- spec/classes/profile/hathitrust/mounts_spec.rb
- spec/classes/profile/hathitrust/perl_spec.rb
- spec/classes/profile/hathitrust/php_spec.rb
- spec/classes/role/htvm_webhost_spec.rb
parallel_test gives each thread an equal number of files to test, so extremely large/slow spec files prevent the tests from getting much parallel speed-up. With that in mind, I split up the tests in the two slowest running spec files: htvm_webhost_spec and all_roles_spec
- htvm_webhost_spec: much of this was effectively testing the profiles required by this role, so I created new profile specs and moved the tests there, and moved tests to existing profile specs where possible. There is more that could be done, I only moved the bits that were obvious, but this is still cuts roughly 20% of the runtime off this file and (I hope) makes the spec a little easier to understand.
- split all_roles_spec into 5 slices: make the logic in all_roles_spec into a function, call it from 5 new spec files
> Test faster

- manifests/profile/networking/firewall.pp
- spec/classes/profile/networking/firewall_spec.rb
- spec/fixtures/hiera/firewall.yaml
This adds $advanced_rules to the firewall profile. These rules get evaluated without any defaults, which allows us to leave some fields empty.
Original post below the fold.
> I'm not going to merge this as is, clearly. Is there any way to have an entry in $rules that ignores everything in $defaults? Two of the three default fields must be empty (not merely different) for a rule I need to add. Tried undef, empty string, and the puppet Default type, none of these worked.
> 
> Worst case, I'll rename $better_tests to something, uh, better, add some tests, and make this a real PR.
> 
> > Error: Failed to apply catalog: Only one of the parameters 'action' and 'jump' can be set
> 
> > Error: Failed to apply catalog: Parameter action failed on Firewall[999 mysql port forwading]: Invalid value …
> add firewall $advanced_rules

- .github/workflows/ci.yml
Pushed a few times with different config to benchmark runners of various sizes.
A "fast" run now cost ~0.15 instead of ~0.25, and takes ~5m instead of ~4m.
Keeping the label for fast running because often we really don't care if it's slow, and I don't want anyone to think twice when making a commit because it costs money, even it the money involved is trivial.
Exact results results below in comments.
> optimal ci runner sizing

- .fixtures.yml
- metadata.json
- spec/defines/cifs_mount_spec.rb
Use regex for present/ensure test this breaks, I'm not fixing that test a third time.
> rollback stdlib version, conflicts with lvm

- manifests/profile/prometheus.pp
- manifests/profile/prometheus/exporter/node.pp
- spec/classes/profile/prometheus/exporter/node_spec.rb
- spec/classes/profile/prometheus_spec.rb
- spec/fixtures/hiera/default.yaml
Until now, prometheus's profile has only been aware of IP addresses in the sense of "every host has exactly 1 IP address, and it's public." That assumption is no longer true; some hosts have 0 public addresses and 1 private address, and most hosts have 1 public address and 1 private address.
1. When the prometheus server is crossing datacenters, it must use a **public** IP address.
2. When the node has 0 public addresses, the prometheus server must use a **private** IP address.
3. The prometheus server should prefer to use a **private** IP address when possible.
4. The prometheus server must be able to fall back to a **public** IP address if there is no available private address.
> Add public/private awareness to prometheus node service discovery

- manifests/profile/hathitrust/networking.pp
- manifests/role/hathitrust/datasets.pp
- manifests/role/hathitrust/ingest_indexing.pp
- manifests/role/webhost/htvm.pp
`private_address_template` is defined all over the place, but it's the same for all HathiTrust hosts. Allow it to be defined in one shared profile.
The advantage of this isn't so much that we get to delete a few lines from the hiera data (which is nice), but that we won't have to add another for each future VM type.
> define private_address_template only once for HT

- manifests/profile/certbot_cloudflare.pp
- spec/classes/profile/certbot_cloudflare_spec.rb
- templates/profile/certbot_cloudflare/commands.erb
Exactly parallel to the Route 53 support, this allows standalone hosts in a Cloudflare zone to get Certbot + Let's Encrypt certificates.
> Support simple certs through Certbot + Cloudflare DNS

- manifests/profile/certbot_cloudflare.pp
- manifests/profile/certbot_route53.pp
- spec/classes/profile/certbot_cloudflare_spec.rb
- spec/classes/profile/certbot_route53_spec.rb
It is apparently not possible to use a file resource to copy something from the fileserver that is symlinked there, even with links => follow.
The other parts of these profiles use concat_fragments, and I used file because I didn't know why. It appears that it is necessary, and this PR aligns the simple cert process with the others.
> Switch from file to concat_fragment for "simple" certs

- manifests/exposed_port.pp
- spec/defines/exposed_port_spec.rb
- spec/fixtures/hiera/exposed_port.yaml
At some point we decided it was important that if we use network block lists like `hathitrust::networks::staff` somewhere other than apache, that we properly handle the case that a block is listed twice:
https://github.com/mlibrary/nebula/blob/962b9b213a0fadd474af7e0aa0e13ecd53815dd6/spec/fixtures/hiera/hathitrust.yaml#L44-L60
I actually need to use `hathitrust::networks::staff` with `nebula::exposed_port`. So, in an effort to _not break_ this canary/test, I added support for duplicate blocks in `nebula::exposed_port`
- `nebula::exposed_port` merges identical blocks
- will still fail if a block name is repeated, but with different content
> nebula::exposed_port: handle duplicate blocks

- .fixtures.yml
- metadata.json
This has an accompanying change in lensoftruth. We have to add the github repo to that Puppetfile.
> Switch from puppetlabs/apache forge module to our fork

- manifests/cert.pp
- spec/defines/cert_spec.rb
This should append `2>&1 | logger -t letsencrypt-renew` to all cert renewal cronjobs.
> Silence letsencrypt cron emails by directing them to logs

- manifests/profile/apt.pp
adoptopenjdk.jfrog.io is gone. If we need this we need to use the new repo temurin/adoptium repo, and we should probably add it to the relevant profiles rather than installing the repo on all Debian hosts.
> remove deprecated adoptopenjdk apt repo

- manifests/profile/hathitrust/cron/statistics.pp
The cron jobs no longer exist at the referenced path, and their output is not really in use. However, we may need to bring these back at some point in another location, so I want to save the reference for them.
> HathiTrust TTO-149 - disable remaining Drupal cron jobs

- manifests/profile/containerd.pp
- manifests/profile/kubelet.pp
- manifests/profile/kubernetes/kubelet.pp
- manifests/profile/prometheus.pp
- manifests/profile/prometheus/exporter/ipmi.pp
- manifests/profile/prometheus/exporter/node.pp
- manifests/role/sysadmin_box.pp
- spec/classes/profile/containerd_spec.rb
- spec/classes/profile/kubelet_spec.rb
- spec/classes/profile/kubernetes/kubeadm_spec.rb
- spec/classes/profile/kubernetes/kubelet_spec.rb
- spec/classes/profile/prometheus/exporter/ipmi_spec.rb
- spec/classes/profile/prometheus/exporter/node_spec.rb
- spec/classes/profile/prometheus_spec.rb
- spec/fixtures/hiera/default.yaml
- templates/profile/kubelet/systemd.conf.erb
- templates/profile/prometheus/config.yml.erb
- templates/profile/prometheus/exporter/ipmi/config.yaml.erb
- templates/profile/prometheus/exporter/ipmi/pod.yaml.erb
- templates/profile/prometheus/exporter/ipmi/scrape_config.yaml.erb
This also creates a generic kubelet profile outside kubernetes, and much of kubernetes's kubelet resources have been replaced with this profile. It's not a complete rewrite, but it's a start.
This should definitely be tested in a development environment before merging.
On the way, this should also fix the naming collision between two different prometheus node exporter packages by pinning to a specific version.
> Add kubelet and ipmi exporter to sysadmin boxes

- templates/profile/prometheus/rules.yml.erb
Currently, the "this is bad" state amounts to "it's been more than 30 minutes since this host last synced with puppet" and we start getting alerts when something has been in that state for at least 30 minutes.
In other words, we find out whenever puppet last synced 1 hour ago.
On its own, in practice, this has not been an urgent alert. Also, we've recently started routine maintenance that involves disabling puppet for hours at a time. Such maintenance already takes roughly 2 hours, so even a 2 hour window could easily be too short.
I think 4 hours should be long enough to avoid drenching us in alerts during planned maintenance without being so long that we wish we'd received an alert sooner.
> Increase PuppetBehind threshold from 30m to 4h

- templates/profile/prometheus/rules.yml.erb
MysqlReplicaSqlDown was confusing to at least one person (me!), who thought it meant "the database is down."
> Rename MysqlReplicationNotRunning alert

- manifests/profile/www_lib/vhosts/apps_lib.pp
This was another case of passive auth running afoul of authz_umichlib.
> Force login for auth system user management app

- manifests/profile/hathitrust/dependencies.pp
FYI @mwarin - after this is merged emacs should generally be available on any HT machine you log in to.
> Martin would like emacs to be generally available on HT machines.

- manifests/profile/kubernetes/destination_port/https.pp
- spec/classes/profile/kubernetes/destination_port_spec.rb
This sends the original client IP in additional metadata outside of the HTTP request. It must be "accepted" by the ingress controller to function.
See also:
* https://www.haproxy.com/documentation/haproxy-configuration-tutorials/client-ip-preservation/enable-proxy-protocol/
* https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/
* https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-proxy-protocol
> Use PROXY protocol from gateway to ingress controllers

- manifests/profile/kubernetes/destination_port/api.pp
- spec/classes/profile/kubernetes/destination_port_spec.rb
- templates/profile/kubernetes/haproxy/services.d/api.cfg.erb
HAProxy's TCP check must be essentially no more than `nc -v`, which was succeeding on a controller node that was very much unavailable. `curl -k` (and `ssh`) was timing out, so this pull request aims to make HAProxy do something closer to `curl -k`. When controller nodes are up and working, as of writing, `curl -k https://addr:6443/` without any attempt at valid client certs yields a prompt `403` status.
> Make HAProxy better at knowing when to pull kubernetes controller nodes from load balancing

- manifests/profile/kubernetes/destination_port/api.pp
- spec/classes/profile/kubernetes/destination_port_spec.rb
If you use the `ssl` option instead of `check-ssl`, then HAProxy will attempt to add its own TLS encryption on top of the TCP forwarding instead of merely letting it pass through. Fortunately, you can use `check-ssl` instead of `ssl`, to tell it only to use SSL on the HTTP check, not on the main load balancing.
> Correctly configure HAProxy to check HTTPS on a TCP frontend

- manifests/profile/www_lib/vhosts/fulcrum.pp
Went ahead and looked into the fulcrum issue from yesterday and I think I correclty updated the change @skorner made.
> move shib require to top location block

- manifests/profile/www_lib/vhosts/fulcrum.pp
The first pass at restoring "badrobots" functionality inadvertently had the global settings to enable shib passively for the Fuclrum vhost within the  config for a require block. This resulted in these settings being ignored and not applied. The changes in this PR address that issue.
> Move global shib settings out of the require block

- spec/classes/all_roles_spec.rb
Test that all roles include nebula::role::minimum, and that all HT roles include nebula::role::hathitrust. In my testing this only adds a few seconds to the test run.
> test all roles include nebula::role::minimum

- .fixtures.yml
- metadata.json
puppet/logrotate 7.0.2 updates puppet/systemd, which conflicts with puppetlabs/postgresql
> pin puppet/logrotate to 7.0.1

- templates/profile/prometheus/rules.yml.erb
I'm starting with `for: 5m` because I'm also setting the severity to ticket, so we don't mind if it's a bit noisy at first. Later we can tweak as needed and consider upgrading its severity to page.
> Add MysqlTooManyConnections alert

- files/imgsrv/catprocio
- manifests/profile/hathitrust/imgsrv.pp
- spec/classes/profile/hathitrust/imgsrv_spec.rb
* Prometheus::Tiny::Shared via CPAN for collecting prometheus metrics in imgsrv
* Script to be run under sudo to allow a process to collect its childrens' final IO metrics
In particular, imgsrv spends much of its time in subprocesses that do a significant amount of I/O. We cannot directly instrument those processes (primarily `unzip` and `grk_decompress`), but would like to monitor some things about them. I have implemented a package in perl (https://github.com/hathitrust/mdp-lib/blob/66a5044a357387289fc60acdf679025b32392553/Utils/MonitorRun.pm#L55) that extends `IPC::Run` to collect metrics from subprocesses after they exit but before issuing a `wait()` system call (that is, the processes are in a "zombie" state). However, after a subprocess exits but before it is reaped, information …
> HathiTrust DEV-1076: support for monitoring for imgsrv

- manifests/local_storage_volume.pp
- manifests/profile/kubernetes/filesystems.pp
Puppet can create and mount (or become aware of) local storage volumes for kubernetes worker nodes. It should not resize or remove volumes.
> Local storage
